### ISSUE TITLE
Enable HTTP Strict Transport Security

### ISSUE THREAD

**Issue by alex** [usds/website#109]
In addition to being a security best practice, it's also required by OMB M-15-13 (lol)

**Comment by konklone** [comment]
Just noting that this might be a good opportunity to get usds.gov preloaded, since the domain is new and unlikely to have subdomains.

**Comment by marcosluis2186** [comment]
@konklone I´m agree with you: this is the perfect time to do it. Even to be more aggressive and include other security headers.

**Comment by tagroup** [comment]
To continue what @marcosluis2186 said, here is a great resource [https://securityheaders.io/?q=https%3A%2F%2Fwww.usds.gov%2F&hide=on&followRedirects=on](https://securityheaders.io/?q=https%3A%2F%2Fwww.usds.gov%2F&hide=on&followRedirects=on).  Current score is an 'E'.

**Comment by davidchang-gov** [comment]
Closing as we do have HSTS (I think it's set too short). Opened a #298 for the other headers.
