### ISSUE TITLE
Copy edit request from SBA

### ISSUE THREAD

**Issue by mebates** [usds/website#122]
Hey team - Aditi Dussault, a senior advisor at SBA and certify.sba.gov guru, has asked for a copy change on the USDS site where it describes the SBA project. The blurb says:

"For small business owners, navigating the contractor certification process is burdensome, involving hours of paperwork and manually scanning dozens of documents. We assisted the Small Business Administration (SBA) in establishing an agile procurement to modernize technology and streamline the certification process. The newly launched certify.SBA.gov saves small businesses time and money, and it increases the SBA’s capacity to provide small businesses access to _the_ federal contracting space **and capital**."

The '**and capital**' portion is not an accurate representation of the project goals at this time. Can it be removed? I added the '_the_' because it sounds awkward without it, to me. 

cc: @mindware

**Comment by cew821** [comment]
Assuming @davidrkaufman is OK with language, the fix in #124 is ready to merge.

**Comment by davidrkaufman** [comment]
Yes, good to go. Thank you Charles!
