### ISSUE TITLE
Change language in repo description

### ISSUE THREAD

**Issue by mollieru** [usds/website#123]
I think we need a @liyanchang for this:

Can you update the wording in 

Currently, we are directing members of the public to leave feedback for USDS.gov here: https://github.com/usds/website/issues

However, the report description (which lives here https://github.com/usds/website) says the following, which is now out of date:

> U.S. Digital Service WhiteHouse.gov website http://www.whitehouse.gov/digital/united-states-digital-service

Instead it should say:

> U.S. Digital Service WhiteHouse.gov website https://www.usds.gov

Similar issue over on the Playbook, where the description reads:

> The U.S. Digital Services Playbook http://playbook.cio.gov

and instead should say 

> The Digital Services Playbook http://playbook.cio.gov

**Comment by liyanchang** [comment]
![screen shot 2016-06-09 at 2 21 58 pm](https://cloud.githubusercontent.com/assets/328073/15941357/bd4fd69a-2e4d-11e6-90b8-3fde9c581969.png)

Fixed.

**Comment by liyanchang** [comment]
![screen shot 2016-06-09 at 2 24 46 pm](https://cloud.githubusercontent.com/assets/328073/15941398/eedf521c-2e4d-11e6-92c5-f584fb1fbf2d.png)
