### ISSUE TITLE
Publish an open source version of this repository

### ISSUE THREAD

**Issue by cew821** [usds/website#126]
This issue replaces #80 

Here's my rough proposal for the migration plan to an open repository. 
- [x] review repository to ensure code and issues are OK to publish
- [x] migrate issues from `/website` repo to this repo
- [x] write a better Readme with information relevant to members of the public
- [x] add a license
- [x] make the new repository public
- [x] update the footer link to point to the new repository instead of the generic issues page
- [x] delete the now deprecated `website` repo

Please feel free to edit this list if I'm missing something.

**Comment by chrisfrommann** [comment]
:+1:

**Comment by nacin** [comment]
👍 . I'd definitely prefer to see this entire repository become public with minimal changes to its code, history, and issues. And if there's anything super problematic in the commit history, we could always force-push over it.

**Comment by mollieru** [comment]
Hi! @chrisfrommann @cew821 @davidrkaufman how's this coming?

**Comment by davidrkaufman** [comment]
@mollieru We should be good here! 

@cew821 Are you ready to push this live

**Comment by mollieru** [comment]
Hi me again, annoying pro-open source nag. We can haz open repo?

**Comment by davidrkaufman** [comment]
@cew821 - Are we good to push this live?

**Comment by cew821** [comment]
Yes, we're good. I'm planning to do this Monday.

**Comment by cew821** [comment]
The repository is now public.

**Comment by ErieMeyer** [comment]
☀️☀️☀️☀️☀️☀️☀️

**Comment by mollieru** [comment]
YASSSS!! Thank you all!!

**Comment by chrisfrommann** [comment]
As a note, the old `website` repo is now `website-v1` and `website-redesign` was renamed to just plain `website`. Woot, woot!

**Comment by unruthless** [comment]
👋  Hi! Thanks for open-sourcing this!

@chrisfrommann Per that name change, I just submitted a pull request that updates the README to reference a repo called `website` rather than `website-redesign`: #190 

Once that pull request is merged in, and since this repo is now open source, I wonder if this issue can be closed? If the "write a better Readme with information relevant to members of the public" and "add a license" subtasks on @cew821's list are still relevant, they could each be split into their own issue.

**Comment by davidchang-gov** [comment]
I deleted the old repo https://github.com/usds/website-v1 given that it was confusing and all the issues were migrated by @cew821 (technically I made it private and waiting 24 hours to see if there are complaints/comments). With #249 and #250, I think we can consider this closed.

**Comment by charwo** [comment]
Thanks much for the cleanup here. closed!
