### ISSUE TITLE
Phase 2: Draft Designs for Header & Footer

### ISSUE THREAD

**Issue by jjoteal** [usds/website#140]
Hi @davidrkaufman,

Here are some draft designs for your review for the next phase of the site:

**New header with About subnav:**
![image](https://cloud.githubusercontent.com/assets/12192706/17224923/8e18e6c2-54c8-11e6-9942-c896bf453c69.png)

**Footer Option 1:**
![image](https://cloud.githubusercontent.com/assets/12192706/17224949/a9c12916-54c8-11e6-8e9a-30fe095f9f04.png)

**Footer Option 2:**
![image](https://cloud.githubusercontent.com/assets/12192706/17224972/be284ed4-54c8-11e6-997d-a0ec5d759add.png)

Let me know your thoughts!

Thanks,
Jess

**Comment by davidrkaufman** [comment]
@jjoteal - Thanks Jess!
- Let's go with Footer Option 1. In previous conversations, it was preferred that we use the seal vs. the WH lockup. 
- For the sub nav, I think the actual animation when you click on about will make it clear, but I'm having a harder time IDing it as a sub nav when static. Not sure if we need the word about again? Maybe we left align the actual sub sections? Will think on it, but @mollieru, would love your eyes as well. 

Thanks!

**Comment by mollieru** [comment]
Exciting @jjoteal !!

**Footer**
I happen to like the layout of the second one better (feels cleaner and more symmetrical), but politics is politics so I get it.

**Nav**
A few questions before feedback: 
- Will all primary nav sections have secondary elements, or just the 'About' ? Do you anticipate adding more secondary sections in the near future (to 'About' or any other). Maybe more of a @davidrkaufman question.
- How do you imagine the interaction working: does it appear on hover or click?
- How do you imagine it working on mobile?

With all that said, I like the look, but also not sure it's quite working -- it's sort of unexpected and thus a little surprising.  

Alternatives: Does all the content fit aligned to the left? How about a simple drop down option instead?  

Here are a few gov drop downs that are using the thick underline as active state for inspiration: 
https://myra.gov/
http://www.consumerfinance.gov/

**Comment by davidrkaufman** [comment]
Right, context is helpful. Sorry about that @mollieru. 

We're working on a few site updates, most substantinial of which is breaking the about section into multiple sections (Mission & Team, Values, Story). 

Will all primary nav sections have secondary elements, or just the 'About' ? Do you anticipate adding more secondary sections in the near future (to 'About' or any other). Maybe more of a @davidrkaufman question.
- **No, only the about section**

How do you imagine the interaction working: does it appear on hover or click?
- **Jess call**

How do you imagine it working on mobile?
- **check out nest.com on mobile. This is what Jess and I looked at as a reference.**

**Comment by davidrkaufman** [comment]
Sorry and one more think @mollieru --the reference you added for myra.gov is good, but we were trying to make it easy for a user to navigate/be aware of the subsections without having to go back to the top nav and hover again.

**Comment by mollieru** [comment]
Awesome -- all very helpful!

Ok, just got a wee bit of second eyes from some 18F UX friends to help me think through this given your above goals. 

Here's what they said (which seems unrelated at first but you'll see how it connects):
- The large circle logo at the top of every primary page gives the impression that we're on a single long page site -- they were confused at first why the top nav wasn't navigating us down the page and how the sub-nav would thus work. 

From this, a suggestion:
- Reserve the large circle logo only for the home landing, and on all other pages, use only the smaller crest (and add a hover state to it). In doing this, we'll create more real estate for secondary nav that doesn't have to fight with the logo for horizontal space -- especially given that you might add more links in the future (to 'About' or another section). 
- In the secondary nav, nix the secondary 'About' and left align the sub-nav. 

And a final two cents (which is, i know i know, a thing I always say): I think the inactive state gray and gray of the background in the sub-nav aren't 508 kosher right now. You could change the background to white (a la https://standards.usa.gov/ ) or maybe have all sub-nav text the same darker hue and indicate active with bold text and an underline. (We'll atleast need the underline since 508 says you should always indicate a link with more than one state change I believe).

Does this make any sense at all? Would it be easier if I sketch things?

**Comment by mollieru** [comment]
PS: can we have this convo in the open repo? 

cc @cew821

**Comment by jjoteal** [comment]
Thanks for the quick feedback @davidrkaufman @mollieru! For ease of combing through the feedback and efficiency, could you guys compile all of your consolidated list of changes into 2 bulleted lists: one for "Required Changes" and one for "Considerations"? That will make it super easy for me to know what I should move forward with for sure, and what I should consider exploring.

 Thanks in advance!

**Comment by davidrkaufman** [comment]
**Required Changes**
- Lock _footer option 2_ - @mollieru, I agree with you on this one. It looks better, I'll deal with the internal conversations if they come up. 
- Reserve the large circle logo only for the home landing, and on all other pages, use only the smaller crest (and add a hover state to it). This will create more real estate for secondary nav th
- In the secondary nav, nix the second 'About' and left align the sub-nav.
- Review @mollieru's feedback re: 508 ( I think the inactive state gray and gray of the background in the sub-nav aren't 508 kosher right now. You could change the background to white (a la https://standards.usa.gov/ ) or maybe have all sub-nav text the same darker hue and indicate active with bold text and an underline.) 

@jjoteal - Your call if a sketch from Mollie would be helpful. 

Thanks all!

**Comment by jjoteal** [comment]
Thanks @davidrkaufman. Will get to these changes Wed or Thu this week!

**Comment by jjoteal** [comment]
Revisions for your review @davidrkaufman @mollieru!

**Revised Header (dark top rail):**
![image](https://cloud.githubusercontent.com/assets/12192706/17375227/b58122ae-5975-11e6-83dc-e75af999ac50.png)

**Revised Header (light gray top rail):**
![image](https://cloud.githubusercontent.com/assets/12192706/17375811/473288d0-5978-11e6-970f-0800096c5e8e.png)

**Approved Footer:**
![image](https://cloud.githubusercontent.com/assets/12192706/17375387/54a0ac42-5976-11e6-979e-3379ea7b7834.png)

Let me know if you have any final changes! Once approved, I can produce the mobile versions.

**Comment by jjoteal** [comment]
@mollieru in the meantime, could you send me a link to the repository for all the various team logos?

**Comment by mollieru** [comment]
@jjoteal yes! it's sort of a mixed bag at the moment -- not every team as a DS-style logo, but the ones we do have are here:

https://github.com/usds/branding/tree/master/DSteamlogos

**Comment by jjoteal** [comment]
Thanks!

**Comment by davidrkaufman** [comment]
@jjoteal - I vote to lock the dark blue top. @mollieru ? 

Also, the Nav reads way better to me. Great feedback, Mollie, on changing the center logo on sub pages

**Comment by alohaj9** [comment]
agree! this new nav is very clear. agree that the dark blue works well, pending @mollieru

**Comment by mollieru** [comment]
Sorrrrry for holding everything up -- I totally missed this! 

Agree all looks much better. Love this Jess! 

One small tweak: we'll need a secondary indicator of current state other than color change in the sub-nav (an underline will do the trick) -- accessibility requirement. 

Nice work!

**Comment by jjoteal** [comment]
Ok, @davidrkaufman and @mollieru, here are the final designs for the new header and footer:

**Final Header**
![image](https://cloud.githubusercontent.com/assets/12192706/17751479/4c45c1f2-6495-11e6-9c61-05ead917669c.png)

**Final Footer**
![image](https://cloud.githubusercontent.com/assets/12192706/17751493/5af0b0d6-6495-11e6-839a-07965036ea2a.png)

I've attached the PSD for the desktop version (had to make it a .zip so it would upload to GitHub)
[usds-header-footer-desktop.psd.zip](https://github.com/usds/website-redesign/files/423555/usds-header-footer-desktop.psd.zip)
 so you can pass along to whomever is doing the front-end development. In the PSD you'll find flattened layers that contained screenshots of the existing page content for Our Story and Our Values. Obviously just ignore those layers and apply the new header and footer when you separate those pages.

Working on the mobile version next...

**Comment by jjoteal** [comment]
And @davidrkaufman @mollieru, here's a draft of the mobile nav, header, and footer:

![image](https://cloud.githubusercontent.com/assets/12192706/17753921/17048022-64a0-11e6-8557-ad09ab043222.png)

Please pass along any feedback!

**Comment by davidrkaufman** [comment]
@jjoteal - this LGTM. I don't think we'll need the option to expand "Our Work" quite yet, but no need to update the design. 

@mollieru - any final feedback?

**Comment by davidrkaufman** [comment]
@jjoteal -- let's move forward with this. Can you please provide @chrisfrommann and I with PSDs for desktop and mobile

**Comment by jjoteal** [comment]
Yep! Here you go @chrisfrommann !

**Desktop:**
[usds-header-footer-desktop.psd.zip](https://github.com/usds/website-redesign/files/427773/usds-header-footer-desktop.psd.zip)

**Mobile:**
[usds-header-footer-mobile.psd.zip](https://github.com/usds/website-redesign/files/427774/usds-header-footer-mobile.psd.zip)

**Comment by davidrkaufman** [comment]
thanks @jjoteal ! Closing this out.
