### ISSUE TITLE
USDS home page Arrows flaky in Safari

### ISSUE THREAD

**Issue by jrminton** [usds/website#141]
If you go to [https://www.usds.gov](https://www.usds.gov) on Safari on Mac, and scroll down to people images, the arrows either don't show up or they partially disappear and/or don't work on mouse over.

**Comment by davidrkaufman** [comment]
@jrminton -- thanks for flagging. 
@chrisfrommann - can you please take a look at this?

**Comment by cew821** [comment]
This was also reported by @benkutil in the old repo:

In trying to navigate forward in the homepage “people” carousel, I had a hard time using the click arrows to move forward and back.

![usds-gov-carousel](https://cloud.githubusercontent.com/assets/228373/15508002/cdefb0b0-219b-11e6-9b3f-53dfa54662e0.gif)

Mac 10.11.55
Safari 9.1.1

[Full Browser Details (PDF)](https://github.com/usds/website/files/279736/browser-details.pdf)

**Comment by davidchang-gov** [comment]
Fixed in #251
