### ISSUE TITLE
Content Hierarchy for Accessibility

### ISSUE THREAD

**Issue by cew821** [usds/website#142]
**This issue was reported by @jamesharnett in the previous public repo**

There is an issue in the order in which keyboard users interact with content, in the **Our work** section of `usds.gov`. As you can see from the "Current" image, the content presentation order makes sense up until it jumps to _Digital Immigration_, skipping over the link to `vets.gov`. This may not seem like a big deal, but for users who depend on using a keyboard and text to speech technology to read to them what is on the page, they may never have known these links existed or would be served them when they were not expecting it.

> "Out of sight, out of mind." Literally.

The solution to this issue is to re-arrange the button's hierarchy inside the rest of the content box, so that the order of highlighted content continues as shown with the "Resolved" image.

This issue can be reproduced for all three columns, and in all three, should be corrected.
## Current

<img width="1280" alt="current" src="https://cloud.githubusercontent.com/assets/4484323/17039139/fb5e29a2-4f66-11e6-9a74-346296492cfb.png">
## Resolved

<img width="1280" alt="resolved" src="https://cloud.githubusercontent.com/assets/4484323/17039147/020a9222-4f67-11e6-8f5f-ea3be15d4b7b.png">
### Reproduction

You can reproduce this issue by enabling VoiceOver (if on a Mac) in System Preferences, reloading `usds.gov`, and tabbing through the site's content (both links and text).

**Comment by jas298** [comment]
@nacingov Would you mind taking a look at this one?

**Comment by nacingov** [comment]
To keep the same design (such that the links in each row are vertically aligned, regardless of the height of the body text), we'd need to move to CSS grid layouts. Or, we could sacrifice the existing design and bring the links directly under the text.

**Comment by jaredcunha-usds** [comment]
I can't think of a compelling reason why those links even need to be aligned. The relationships are with the content above them rather than each other.

**Comment by jas298** [comment]
@nacingov @jaredcunha-usds I agree with Jared; I see no reason why the links can't be immediately below the text. 

@sarahsaltiel thought?

**Comment by sarahsaltiel** [comment]
I agree, that makes sense @jaredcunha 

Would we be able to see what that looks like?

**Comment by jaredcunha-usds** [comment]
This is what it would look like:

<img width="1089" alt="screen shot 2017-05-26 at 9 55 20 am" src="https://cloud.githubusercontent.com/assets/25435289/26497438/827bd3fa-41f9-11e7-94bf-9cec356fc8dd.png">

**Comment by jaredcunha-usds** [comment]
I have this PR if the design edits look good.
https://github.com/usds/website/pull/318

**Comment by jas298** [comment]
Changes look fine to me; @sarahsaltiel are you good with them? If so, I will merge #318.

**Comment by sarahsaltiel** [comment]
Looks good @jas298 @jaredcunha
