### ISSUE TITLE
"Now Leaving" interstitial is not always big enough

### ISSUE THREAD

**Issue by cew821** [usds/website#145]
With a long link, the box is too small: 

![image](https://cloud.githubusercontent.com/assets/1237498/17262607/5baa2560-55aa-11e6-8b91-60266a60ea38.png)

**Comment by chrisfrommann** [comment]
The box no longer has a fixed height and I added 'word-wrap: break-word;' to 'you are now leaving' URLs; see PR #192

**Comment by cew821** [comment]
Nice. I am closing this.
