### ISSUE TITLE
Phase 2: Draft Designs for "Our Work" Landing and Individual Project Page

### ISSUE THREAD

**Issue by jjoteal** [usds/website#152]
Hello @davidrkaufman @alohaj9 @mollieru 

Thoughts on this for a modified "Our Work" landing page (to meet the objective of incorporating the team logos):

![image](https://cloud.githubusercontent.com/assets/12192706/17409467/0a278a86-5a35-11e6-8a91-43b708cc1afb.png)

Clicking on the image or title of the project would go to the Individual Project page which would include the full write-up about the project and a prominent link to the actual product (to be designed yet). And, clicking on the team shield or team name would link to the separate subsites for the Individual teams. Or of course, we could have separate team landing pages, which would display the projects "owned" by that team in this same landing page format.

Thoughts on this approach?

**Comment by davidrkaufman** [comment]
Would love feedback from @alohaj9 and @cew821, who I know has also been thinking about this. 

I like the idea of integrating team logos--only complications are 1) teams that don't have a logo yet (HHS, for example) and 2) projects that are collaborations between multiple teams. 

Regarding what we link out to, we don't have built out pages yet for each project, but I think we'll get to this point. Maybe we just start with these being non-clickable images and build out from there?

**Comment by cew821** [comment]
I like this idea, however most teams don't have unique logos (especially teams that are "in progress" like HHS), and many projects are cross-functional in nature so won't have a natural logo. So I think this may not work as well in practice, unless we are OK with only some of the projects having a logo.

**Comment by davidrkaufman** [comment]
@cew821 @jjoteal 

Yeah, good point charles. Let's hold on this for the moment until all teams have logos. We can focus efforts on the new about pages for the time being. 

Thanks!
