### ISSUE TITLE
Content Hierarchy for Accessibility

### ISSUE THREAD

**Issue by jamesharnett-zz** [usds/website#156]
Bumping [issue #54](https://github.com/usds/website/issues/54) from [usds/website](github.com/usds/website).

**Comment by cew821** [comment]
Thanks James - I actually already ported that over in #142 so closing this as a dupe. Thank you so much for reporting it, it is in our backlog.

**Comment by jamesharnett-zz** [comment]
Sorry, didn't see it. Thanks!
