### ISSUE TITLE
Phase 2: Draft Design for Mission & Team Page

### ISSUE THREAD

**Issue by jjoteal** [usds/website#157]
Hello again @davidrkaufman and @mollieru!

Here is the draft Mission & Team page for your review. I figured using the illustrations on this page would be a good way to carry out that overall aesthetic. Will we need an HQ seal sketch though... And of course, you should feel free to place the teams in any order you see fit.

Let me know your thoughts!

![image](https://cloud.githubusercontent.com/assets/12192706/17755717/937c27dc-64a9-11e6-8e92-4a3c1ba6cd87.png)

**Comment by davidrkaufman** [comment]
Thanks @jjoteal -- this looks great to me! Very simple and clear. Let me confirm with Mikey or Haley which teams should be included in our network. If it scales up or down, I'm assuming we just continue the 2-3-2 pattern? Only other contigency would be @nguyenist having time to do a few watercolors for this. 

@mollieru - design FYI 

@cew821 @chrisfrommann - development FYI

**Comment by jjoteal** [comment]
@davidrkaufman cool. Yes, we would continue the 2-3-2 pattern. And yes, we'd need @nguyenist to create new watercolors for any new teams, in addition to creating one for HQ.

Let me know if the team has any design changes and I'll be ready to make them!

**Comment by davidrkaufman** [comment]
@nguyenist has tenatively signed on for this :) 

stay tuned--will check w Mikey re: teams ASAP

**Comment by davidrkaufman** [comment]
@jjoteal -- barring any feedback from Mollie, we'll move forward here. Can you please provide @chrisfrommann and I with PSDs for this and the mobile design? Thanks!

**Comment by jjoteal** [comment]
Sure thing @davidrkaufman. I can have the mobile version for you early next week, but here is the desktop version PSD:
[usds-mission-desktop.psd.zip](https://github.com/usds/website-redesign/files/427777/usds-mission-desktop.psd.zip)

**Comment by davidrkaufman** [comment]
Thanks @jjoteal. CC: @chrisfrommann

**Comment by jjoteal** [comment]
@davidrkaufman @chrisfrommann 

**Here is the mobile version:**
![image](https://cloud.githubusercontent.com/assets/12192706/17895131/0feff2de-691a-11e6-9584-45636cdfefc5.png)

**And here is the PSD:**
[usds-mission-mobile.psd.zip](https://github.com/usds/website-redesign/files/432608/usds-mission-mobile.psd.zip)

**Comment by mollieru** [comment]
Hi sorry for radio silence! 

 I think this looks real good! Depending on the amount of text, might look nice to have the 'mission' body text in a larger font size (like the serif body font on the 'about' page).

I suggest we put the content in before signing off on the layout since in the first release the content changed the spacing needed.

**Comment by davidrkaufman** [comment]
@mollieru Thank! I'll be sure we get a design review in once the content is actually plugged in.

**Comment by davidrkaufman** [comment]
@jjoteal -- re-opening this with a minor update. 

Given that the question continues to come up with recruits, I'd like to better differentiate official USDS teams (USDS, VA, DOD, DHS) from teams we're partnering with (Ed, State, HHS, Treasury, Justice, SBA). 

Could we add text to divide up the two sections. For the moment we can use. 

U.S. Digital Services Teams 
{seals for DoD, VA, DHS}

Actively partnering with
{sealing for remainder}

cc: @nguyenist - locked this with Mikey, so visual needs are: 
- Digital Service shields from DDS, VA Digital Service, and DHS Digital Service (we have USDS already)
- Agency shields for SBA, Treasury, Justice 

cc: @chrisfrommann as FYI for the build

**Comment by davidrkaufman** [comment]
@jjoteal @nguyenist @chrisfrommann - hold on this for the moment. more details likely to come today

**Comment by jjoteal** [comment]
Sounds good @davidrkaufman . Also, as a heads up, my email wrongly migrated to the new server, so they are moving me back today (in theory). As of now, I'm unable to access email, so if you need to reach me quickly, text me at 248.760.3656.

**Comment by nguyenist-zz** [comment]
@davidrkaufman hey let me know once the convos around finalizing what seals / images we need on the about page happen / are approved before i work on them.

**Comment by davidrkaufman** [comment]
@chrisfrommann 

here's the copy. thanks for being USA #1. 
[Website Updates.docx](https://github.com/usds/website/files/523060/Website.Updates.docx)

**Comment by davidrkaufman** [comment]
@jjoteal @mollieru @nguyenist @alohaj9 - FYI, this is now live, minus the network of teams section. Additionally Chris is still working on implementing on mobile. @chrisfrommann: When do you expect the mobile version to be displaying properly?

**Comment by chrisfrommann** [comment]
@davidrkaufman, mobile is all done -- see PR #193!

**Comment by davidrkaufman** [comment]
Thank you!

**Comment by davidrkaufman** [comment]
@chrisfrommann @nguyenist 

Reviving this thread with a final decision. We'll maintain Jess' initial design, and include the agency shields (the proper agency shield...ex: VA, not VA DS) for: 

Ed
HHS
DoD
State
DHS
VA
TREASURY
SBA

ACTION ITEMS: 
- **Chris**: Can you start putting together the build for this page, which will live on the current "Our Mission" section of the site.  A few minor changes/updates from Jess' design: 

1) We will no longer list agency leadership next to each shield. We will only list the team name. 
2) Once we add this to the "Our Mission" page, that section should be renamed "Mission & Team" in the nav
3) USDS HQ will not be listed
- **Steph**: Can you please put together the water color shields for the teams we are currently missing. I believe those are Treasury, SBA, State.

**Would love to get this live by Nov 1. Please let Janine and I know if that is reasonable.**

Thanks all!

cc: @alohaj9

**Comment by nguyenist-zz** [comment]
@davidrkaufman Sounds good. Breaking this out into different issues so it doesn't get lost in this thread. See: #201

**Comment by nguyenist-zz** [comment]
@jjoteal @chrisfrommann I uploaded the shields separately so we can do these screens. Is this still current even though we are not doing a shield for usds?
![image](https://cloud.githubusercontent.com/assets/4484141/19621431/da7a1308-985f-11e6-9ed7-6dcacd159ea5.png)
and
![image](https://cloud.githubusercontent.com/assets/4484141/19621435/e2348dda-985f-11e6-94c2-1e6963d51ac1.png)

**Comment by davidrkaufman** [comment]
@nguyenist - still current, but @jjoteal, we now have 8 shields. How would you like us to lay these out on desktop?

**Comment by alohaj9** [comment]
@chrisfrommann - do you have an ETA for this update? Ideally, we'll have this live by November 4th. Thank you!

**Comment by davidchang-gov** [comment]
We've implemented the mission page and have drawings for all the agencies. Thanks!
