### ISSUE TITLE
Higher resolution / responsive splash image

### ISSUE THREAD

**Issue by alexose** [usds/website#188]
As a visitor to the USDS front page, I want to see all of your lovely faces in the group photo.

We could use a higher resolution photo with [srcset](https://css-tricks.com/responsive-images-youre-just-changing-resolutions-use-srcset/) without sacrificing performance on smaller screens.

Thank you!

**Comment by askldjd** [comment]
Thank you for being awesome.

**Comment by chrisfrommann** [comment]
Thanks for the flag, @alexose! We only had one (low-res) version of the image to start, but we got the original and I'm updating it now with multiple versions (we'll probably start with different resolutions, but may want to change the cropping/composition later -- TBD).

**Comment by chrisfrommann** [comment]
See PR #189
