### ISSUE TITLE
508 Issues - Home, Story

### ISSUE THREAD

**Issue by nickbristow** [usds/website#19]
Just checking out the site, and noticed a couple of minor 508 issues you might want to address. 
Let me know if you have any question or would like to chat. I can also do a formal audit if you think that would be beneficial to you all. 

1. Skip Nav 
  * Your skip nav is good, but to make it more compatible with different browsers add tabindex='-1' to the target anchor. This will give it "true" focus allowing a user to keep tabbing from that point. You can hide the outline on this div so it doesn't show when someone clicks on it and because it's "-1" it won't show up in normal tab order
2. The USDS logo is a CSS image. Important images should be on the page with an img tag so a screen reader user can hear the alt tag
3. Images in 'The Work' section should have more descriptive alts.
  * Text in the images should be included in the alt
  * Different images shouldn't have the same alt
4. Images of 'The People' are missing alt tags
5. The rollover functionality for the headshots, is not accessible with just a keyboard 
6. For 508, the goal is 4.5:1, this can be verified with any OTS color contrast analyzer. I only noticed a sing spot (not counting the header and footer, from the parent site) where it missed
  * ![us_digital_service_recruitment_-_home___the_white_house]
(https://cloud.githubusercontent.com/assets/5296248/5824978/1fe43f2a-a0b6-11e4-8074-c6c9116dc10f.png)
7. Image alts should have the exact text from the image
  * ![us_digital_service_recruitment_-_the_story___the_white_house](https://cloud.githubusercontent.com/assets/5296248/5825381/e1f0be5c-a0b8-11e4-9173-e952d22495fa.png)

**Comment by mollieru** [comment]
@nickbristow this is awesome thank you!  Quick (and annoying, sorry) favor: could you pull out another issue with all of the feedback about the /apply page? That's being built in Salesforce and different folks have the ability to make changes there.  CC @kathytpham

**Comment by nickbristow** [comment]
Done

**Comment by kathytpham** [comment]
Thanks @nickbristow <https://github.com/nickbristow>! Can you please
clarify "Use fieldset and legend for groups of form inputs"? The Salesforce
team is making updates and I couldn't clarify that point for them.

Thanks!

On Tue, Jan 20, 2015 at 2:56 PM, mollieru <notifications@github.com> wrote:

> @nickbristow <https://github.com/nickbristow> this is awesome thank you!
> Quick (and annoying, sorry) favor: could you pull out another issue with
> all of the feedback about the /apply page? That's being built in Salesforce
> and different folks have the ability to make changes there. CC @kathytpham
> <https://github.com/kathytpham>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhiteHouse/usds-website/issues/19#issuecomment-70751895>
> .
>



-- 
912-220-6423
kathytpham@gmail.com

**Comment by nickbristow** [comment]
@kathytpham 

Sure thing. Fieldset and legend is used to group related field forms and provide their instructions. 

For example, 
```
<fieldset>
<legend>Prior Address</legend>
<label for="street">Street Address</label> <input id="street" type = "text">
<label for="city">City</label> <input id="city" type = "text">
<label for="state">State</label> <input id="state" type = "text">
</fieldset>
```
All these fields are related grouped in a ```<fieldset>``` tag. This group also has a ```<legend>``` tag. The legend provides additional information, needed to fill out those fields. Without it, a screen reader user would just hear, "Street Address" and not "Prior Address, Street Address." 

I've marked up this set here as an example. Let me know if this all makes sense. 
![us_digital_service_-_apply___the_white_house](https://cloud.githubusercontent.com/assets/5296248/6178913/c708745a-b2e1-11e4-9f45-f7d1989b5683.png)

**Comment by mollieru** [comment]
@chasekimbrell @kathytpham @nickbristow did this get resolved for the application page?
