### ISSUE TITLE
Update Press Links

### ISSUE THREAD

**Issue by davidrkaufman** [usds/website#195]
Hey Chris/Charles, 

Can you please help update the press section of the site with three additional links: 

Star Spangled Geeks: https://backchannel.com/inside-the-obama-tech-surge-as-it-hacks-the-pentagon-and-va-8b439bc33ed1

To Fix Government Tech, Take Off the Headphones and Listen: https://shift.newco.co/hands-off-the-keyboard-innovation-lessons-from-inside-the-us-government-1c9f592f8e5e#.b07c23sln

Government as Software Builder, Not Just Buyer: http://a16z.com/2016/07/13/usds/

Thank you

cc: @alohaj9

**Comment by chrisfrommann** [comment]
Live now
