### ISSUE TITLE
Illustrate agency shields for: Treasury, SBA, State

### ISSUE THREAD

**Issue by nguyenist-zz** [usds/website#201]
Creating: 
- Treasury
- SBA
- State

@davidrkaufman let me know if there are any missing

**Comment by nguyenist-zz** [comment]
@davidrkaufman realized we already have State logo on the website, so only needed to create Treasury and SBA. See PR #202.

**Comment by davidchang-gov** [comment]
#202 fixes this issue so closing. Thanks!
