### ISSUE TITLE
Benefits Tab on Join Us is Blank

### ISSUE THREAD

**Issue by davidrkaufman** [usds/website#209]
The copy that should appear under the benefits tab is showing at the bottom of "who we're hiring". I'm not sure why after checking out the HTML.

**Health insurance**

All joining full-time for more than three months are eligible to receive health insurance. Many employees will also be eligible for dental and vision plans and will be automatically covered by basic life insurance with the option to elect into additional coverage. Your HR contact will go over the benefits that apply to your offer.

**Retirement**

Many employees joining the U.S. Digital Service for at least one year will be eligible for the Thrift Savings Plan, the government’s version of a 401k, which offers up to five percent matching.

**Commuter**

Employees who commute by public transportation may receive subsidies for commuting costs. This benefit aims to reduce traffic congestion, conserve energy, and improve air quality.

**Comment by davidrkaufman** [comment]
@chrisfrommann the friendliest of pings

**Comment by chrisfrommann** [comment]
Fixed ✅
