### ISSUE TITLE
[Join Us] Add character counter to "Anything else we should know?" textarea

### ISSUE THREAD

**Issue by lizmueller** [usds/website#224]
Adding a character countdown to show the remaining characters (like [this JSFiddle](http://jsfiddle.net/timur/47a7A/)) would improve usability of the Apply Now/Join Us form.

Textarea ID = appPage:appForm:whyJoin

**Comment by kwokster10** [comment]
I was playing around with the page and it looks like the following can be added to the iframe to get this functionality: 

```javascript
var textarea = document.getElementById("appPage:appForm:whyJoin");

var textareaFeedback = document.createElement('div');
textareaFeedback.setAttribute("id", "textarea-feedback");
textareaFeedback.setAttribute("style", "font-size:small; font-weight:normal; font-style:italic;");
textareaFeedback.innerHTML = "500 characters remaining";

textarea.parentNode.appendChild(textareaFeedback);

textarea.maxLength = 500;
textarea.onkeyup = function() {
    var textLength = textarea.value.length;
    var textRemaining = 500 - textLength;

    textareaFeedback.innerHTML = textRemaining + ' characters remaining';
};
```

It would need to be added to to the iframe with Salesforce though, otherwise it throws a `cross-origin frame` error.

**Comment by jaredcunha-usds** [comment]
We have a new form that will be available soon that addresses this issue. Thanks for raising! Would have been overlooked otherwise!
