### ISSUE TITLE
USDS/Join page

### ISSUE THREAD

**Issue by neilmartis** [usds/website#225]
Hi All

The Current USDS join page takes me to the Salesforce Page when asking users to join with the EOP email address dl-oa-salesforceadmins@oa.eop.gov
![screen shot 2016-12-15 at 11 36 30 pm](https://cloud.githubusercontent.com/assets/10228512/21251859/86dc0d56-c31f-11e6-8da0-f1d39a61099e.png)
Thanks,
Neil

**Comment by chrisfrommann** [comment]
Flagging for @briandroberts (CC: @alohaj9, @davidrkaufman)

**Comment by neilmartis** [comment]
@chrisfrommann @alohaj9 @davidrkaufman I also submitted a pull request if that help to bring back the original form

**Comment by chrisfrommann** [comment]
Thanks for that, Neil -- unfortunately that form won't work. We're looking into what went wrong with Salesforce -- thanks so much for bringing it to our attention!



On Dec 16, 2016, at 8:40 AM, Neil Martis <notifications@github.com<mailto:notifications@github.com>> wrote:


@chrisfrommann<https://github.com/chrisfrommann> @alohaj9<https://github.com/alohaj9> @davidrkaufman<https://github.com/davidrkaufman> I also submitted a pull request if that help to bring back the original form

-

**Comment by neilmartis** [comment]
@chrisfrommann Glad to help.
