### ISSUE TITLE
Add "Play Video" Button to Homepage

### ISSUE THREAD

**Issue by dkaufman36** [usds/website#227]
Chris--

In prep for the video launch, can you please add a button on the first section of the homepage that says "Play video" and opens up a YouTube video player window?

Reference: https://nest.com/thermostat/meet-nest-thermostat/

**Comment by dkaufman36** [comment]
@chrisfrommann know you're in CHI, but bumping this to ensure it's on your radar. Have to have this live for Monday :1st_place_medal: !

**Comment by chrisfrommann** [comment]
Done
