### ISSUE TITLE
Copy Missing from Homepage

### ISSUE THREAD

**Issue by dkaufman36** [usds/website#230]
It appears the H2 for "Our work" went missing on the homepage. Believe this is a simple fix, but I don't have my mac so didn't want to touch anything. 

Intricate bug report attached. 
![where did our work go](https://cloud.githubusercontent.com/assets/24896125/21688187/d857fc2e-d339-11e6-8ef6-4035faf5b031.PNG)

Assigning to Chris, but cc'ing @alex who has had record response time recently, if he can fix first.

**Comment by neilmartis** [comment]
@davidrkaufman Made a pull request for it

**Comment by dkaufman36** [comment]
@chrisfrommann bumping this if you can resolve today please

**Comment by chrisfrommann** [comment]
Fixed in `master`
