### ISSUE TITLE
Changes for Congressional Report

### ISSUE THREAD

**Issue by dkaufman36** [usds/website#233]
Nacin, 

To keep us organized, I wanted to add all changes to one issue. Once the report is ready for the site we should: 

1)  Add a subnav to "Our work" in the site header. Our two sub nav options will be: "Portfolio" and "2016 Report to Congress" 

2) On the homepage of USDS.gov, put a blue banner after the "Solving Big Problems" section that looks something like the below. 

![report banner](https://cloud.githubusercontent.com/assets/24896125/21722323/14dc23ee-d3fa-11e6-82a1-5b42c9a6fb60.PNG)

Copy should read: 

- New: 2016 Report to Congress
- Read the U.S. Digital Service Report to Congress: the most comprehensive review of our work to date.

3) On the existing "Our work" page, update the body copy to: 

"We live in a world where any new public policy is only as good as its underlying technology. Explore a few of the projects we've tackled below. For a comprehensive review of our most important projects to date, read the 2016 U.S. Digital Service Report to Congress {link}"

4) Add "2016 Report to Congress" to the Reports footer

5) Bonus points: The impact report currently in our footer will likely disappear with the new WH.gov on Jan 20. Can you please PDF the existing and host in on our site so the link doesn't break? PDF is fine for this report, as it should maintain the feel of a past document from the Obama Admin. https://www.whitehouse.gov/the-press-office/2016/08/09/impact-report-transforming-government-services-through-technology-and?_ga=1.52677480.1161200624.1469652494

cc: @alohaj9 @cew821

**Comment by nacin** [comment]
Paging @chrisfrommann. The nav CSS will need some tweaking to allow for the second submenu nav, and he'd likely get that done a few times faster than I could. Halp.

Otherwise I will continue to focus on getting the report pages ready. We can work in a public PR here for everything but the report text.

Items 2-5 here are straightforward and if Chris has time, awesome, otherwise I will handle. Just noting that the URL will be `www.usds.gov/report-to-congress/2016/`.

**Comment by chrisfrommann** [comment]
I can do this tonight, but back to back until 5p.

**Comment by nacin** [comment]
@chrisfrommann I hope to wrap this up this weekend, to give you an idea of timing. Not going live until later next week (at earliest).

**Comment by nacin** [comment]
@dkaufman36 For bonus points, should that instead be a new page, rather than a PDF? PDFs are sad.

**Comment by nacin** [comment]
Never mind, I see your clear justification above.
