### ISSUE TITLE
What's the minimum supported browser?

### ISSUE THREAD

**Issue by username1290** [usds/website#254]
Hi, wanted to know what are the oldest browsers that the USDS supports?

Thanks

**Comment by nacingov** [comment]
Hi @sogen, it depends on the project. Following the USDS Playbook (https://playbook.cio.gov), we use data to drive these decisions. Browser usage across government websites, which can be seen on the [analytics dashboard](https://analytics.usa.gov/), can be variable depending on the populations using the service. Similarly, an internally-facing system used only by government employees may be able to get away with supporting less browsers than a public-facing system. (Of course, depending on the agency, that could be anywhere from IE9 [though we see this less often now] to Chrome.)

**Comment by username1290** [comment]
👍
