### ISSUE TITLE
tomlaheyh@gmail.com

### ISSUE THREAD

**Issue by tomlaheyh** [usds/website#256]
Its more than amazing that you don't have an email for people to send comments, information, questions. You can put in a note that your don't have time to personally answer all questions, but will try with the limited resources you have. Next put an auto responder with a "thanks for your email etc." You don't even have to look at a single email (although that would be good...) at least fake being responsive, people will appreciate it. This might allow those of us who actually have good questions or suggestions a chance to get through.  Github is way to geeky for the majority of the public and if making things easy and accessible is what you're about you get a failing grade.

**Comment by charwo** [comment]
Thanks for the feedback Tom.
