### ISSUE TITLE
Left and right sides of Join us form are cut off

### ISSUE THREAD

**Issue by kwokster10** [usds/website#261]
While on a 13" laptop, I noticed the left side of the Join us form is cutoff. This causes the checkboxes to be missing it's left border and all of the form fields highlighting are cut off on focus. 

<img width="654" alt="desktop view" src="https://cloud.githubusercontent.com/assets/11097983/22623289/48531698-eb23-11e6-9193-f94c23803ea3.png">

Opening the console and toggling the devices show that this also effects the mobile experience. In fact on mobile, the select boxes and labels of checkboxes are all cut off.

<img width="416" alt="mobile view" src="https://cloud.githubusercontent.com/assets/11097983/22623286/3201432e-eb23-11e6-9590-09dddd4f8f94.png">

It appears there are hard widths set on the elements from the salesforce `digitalserviceform` asset and also the `uswds.min.css` file.

**Comment by jaredcunha-usds** [comment]
It seems to be combination of that and perhaps a need for padding on the `<body>`. Does anyone know where the form might be? @davidchang-gov

**Comment by davidchang-gov** [comment]
The iframe is hosted on Salesforce. So @jas298 and @briandroberts will have to help out. I'm sure they'd appreciate you finding the right css to do the right things and then they can help deploy.

**Comment by jas298** [comment]
Yes, we tried to fix this, ultimately broke something else, and haven't come back to it. @jaredcunha if you want to sit down next week and look at this in Salesforce, I'd be happy to do that. @briandroberts is also around JP this week if you want to do it now!

**Comment by jaredcunha-usds** [comment]
@jas298 I'm between projects at the moment so I can definitely help out with this. @briandroberts, let me know when you're around and we can knock this out.

**Comment by jaredcunha-usds** [comment]
For what it's worth, I do have some code that is ready to go. However, there are inline styles using `!important` (which is just cruel 😐) that we need have taken out.

**Comment by davidchang-gov** [comment]
Fixed! Thanks @jas298!
