### ISSUE TITLE
Redirect from whitehouse.gov disappeared

### ISSUE THREAD

**Issue by ayaleloehr** [usds/website#281]
https://www.whitehouse.gov/digital/united-states-digital-service used to be the USDS website before we got usds.gov.  There are still many links online to the old URL, which it no longer redirects to usds.gov and instead returns a 404. Any chance we can make this old URL start redirecting again?

**Comment by davidchang-gov** [comment]
Looking at Google analytics -> Acquisition -> Source

From Dec 1 -> Dec 31 of 2016:
Of 12,724 session, 8 came from whitehouse.gov and none of those submitted an application.

Therefore, given that it's going to be a thing every 4-8 years, it's best that we use the usds.gov domain.

Thanks for pointing this out!

**Comment by ayaleloehr** [comment]
Making decisions with data? Fine. :)
