### ISSUE TITLE
Add Digital Analytics Program (DAP) tracker to usds.gov

### ISSUE THREAD

**Issue by justgrimes** [usds/website#303]
Recommend adding Digital Analytics Program (DAP) tracker to usds.gov

For reference, Digital Analytics Program (DAP) is a central, shared web analytics service for federal agencies of the United States government, managed by the General Services Administration. Participating federal agencies report web analytics to a central account, and have access to all reported data. Data from the program is also shared publicly at analytics.usa.gov.

Adding DAP tracker code in public facing agency websites are required by OMB Memorandum M 17-06, Policies for Federal Agency Public Websites and Digital Services. See https://obamawhitehouse.archives.gov/sites/default/files/omb/memoranda/2017/m-17-06.pdf

Use Analytics and User Feedback to Manage Websites and Digital Services 

All public facing websites and digital services should be designed around user needs with datadriven
analysis influencing management and development decisions. Agencies should use
qualitative and quantitative data to determine user goals, needs, and behaviors, and continually
test websites and digital services to ensure that user needs are addressed.

All agencies must participate in the General Service Administration’s (GSA) Digital
Analytics Program (DAP) and deploy the DAP tracking code on all public facing agency
websites. The DAP provides agencies with free quantitative analytics to inform website
management. Participation in the DAP does not preclude agencies from using other analytics
program.

**Comment by jas298** [comment]
@nacingov Can you please look into this?

**Comment by jaredcunha-usds** [comment]
@nacingov @jas298 #317 is looking good. Gonna take this issue and move to the Review column.
