### ISSUE TITLE
nav bar should link to @USDS on Twitter

### ISSUE THREAD

**Issue by afeld** [usds/website#31]
Currently goes to @whitehouse.

![screen_shot_2015-01-22_at_1_28_08_am](https://cloud.githubusercontent.com/assets/86842/5851492/18fa9ee0-a1d6-11e4-9e7a-1ec5e892b240.png)

**Comment by mollieru** [comment]
Unfortunately I'm not sure we have the ability to change this. Will work on finding out from the WH team.

**Comment by neilmartis** [comment]
I can update the link did thru chrome and firebug do let me know if I can do that for you

**Comment by neilmartis** [comment]
![usds1](https://cloud.githubusercontent.com/assets/10228512/13206221/695120b6-d8c7-11e5-91b5-90f02e7be0dc.png)

**Comment by neilmartis** [comment]
I don't have access to the files to change them,is it possible to provide me with access

**Comment by mollieru** [comment]
Neil, the USDS website is currently just a page on the whitehouse.gov Drupal site; thus we follow their conventions wrt to site UX patterns such as nav bat styling etc. (Relatedly, this is why our pages are not currently available on Github).

We are working on a redesign, so stay tuned in the coming months!

Thanks for your feedback and engagement.



Mollie Ruskin
U.S. Digital Service

-----Original Message-----

**Comment by neilmartis** [comment]
I would be glad to help with the design.Do let me know I can ping you via Twitter or something.I want to contribute to it.

**Comment by neilmartis** [comment]
Thanks Mollie
