### ISSUE TITLE
Tweak typography at smaller viewports

### ISSUE THREAD

**Issue by noahmanger** [usds/website#33]
The typography could be optimized for mobile viewports (excuse the huge screenshots).

A few places caught my eye:

These `<h3>`'s could be smaller / reduced to fewer lines:
![img_1686](https://cloud.githubusercontent.com/assets/1696495/5863456/afc476cc-a247-11e4-9290-6e468d960623.PNG)

The line height on these headers should/could be reduced: 
![img_1687](https://cloud.githubusercontent.com/assets/1696495/5863478/e088ae5e-a247-11e4-9575-be62517b6434.PNG)

The column width on the profile blurbs is too narrow and breaking weird:

![img_1688](https://cloud.githubusercontent.com/assets/1696495/5863490/f0e9fa32-a247-11e4-828c-a29ab16feab3.PNG)

**Comment by mollieru** [comment]
Yes! Thanks for catching this. it was on our nice-to-have list to fix for launch, and want to get back to it now. Good stuff.

**Comment by mollieru** [comment]
@noahmanger if I send you the .html file, would you want to take a crack at helping me make this better?

**Comment by noahmanger** [comment]
Sure thing, though it's more of a CSS issue I think. But yeah, send me whatever you have.

**Comment by cew821** [comment]
I am also happy to help with this, I agree it should be done in CSS. I can wrangle the CMS pretty easily if we had a better idea of what we're angling towards. I guess just reducing the right margin, and bumping down the font sizes a bit? What else?

**Comment by noahmanger** [comment]
Looks like the issue on the people divs is that the width is fixed at 221px. Not sure what the breakpoints are, but I'd do something like setting the `.usds-person { width: 50%; }` for tablets and `.usds-person { width: 100%;}` for phones. 

Looking at the photos / quotes, though that leaves them a little awkward. I'd refactor the markup a bit so that you're not absolutely positioning the photos, that way you can center them above the content, whatever the width.

**Comment by noahmanger** [comment]
Sorry if that's a little tough to follow. Again, happy to get into the code directly too.

**Comment by cew821** [comment]
That's helpful, thank you. I will try to do a few of these today... the Circles will be the most significant one I think. I promise we actually do know how to do frontend development here... this CMS tho... :open_mouth:

**Comment by mollieru** [comment]
Anyone want to take a peak and see how things are looking nowadays?
