### ISSUE TITLE
Applicants submitting application, not receiving confirmation email and application not populating in salesforce

### ISSUE THREAD

**Issue by sarahsaltiel** [usds/website#330]
At first I thought it was user error, as I was able to submit. However, we've received 3 - 5 complaints about this issue over the past 2 weeks which I consider high. Any way for us to look into this..?

PS Nadia has specific names/dates for when this has happened.

**Comment by nacingov** [comment]
I have no insight into the Salesforce integration. We'll need to ask OA for help if @jas298 doesn't have appropriate accesses or insights. Also possible we can enlist @kimballce.

**Comment by nadiay123** [comment]
Here are times that we've recieved emails about applications or resumes not going through. 
If OA / Jenny need names I'll send those along separately, but leaving timestamps here as an FYI for now. 

 No Application - 5/23: Midnight ish? 
 No application: 5/24:11:54 AM 
 Resume error : 5/30 11:00 PM 
 No application:  6/11 1:10 PM

**Comment by sarahsaltiel** [comment]
More issues reported from other members of talent. Do you know someone we can call in OA @nacingov ? Jenny's out of the country til next week.

**Comment by sarahsaltiel** [comment]
Spoke to brian today about what to do - emailing Dylan Kaufman from OA. Trying to recreate the issue.

**Comment by nadiay123** [comment]
Adding updates here - in case anyone is following along: 
Looks like it might be tied to people going over the 500 character limit (and the website counting the spaces?) 
Unclear - but had 2 new candidates mention this issue today.

**Comment by nadiay123** [comment]
also related issue: https://github.com/usds/website/issues/224

**Comment by jas298** [comment]
I agree with the hypothesis that this is due to people going over the 500-word limit, because when they do and they get an error, it's really hard to spot. However, not sure if that is the case. @sarahsaltiel, can you please add me to your thread with Dylan and I will follow up with him?

**Comment by jas298** [comment]
To update--Dylan and I both do not see an errors on the backend. I do think this is due to people going over 500 characters and not seeing the error message. Tackling those two issues at:

- character limit: #337 (related, #224)
- error page styling: #299
