### ISSUE TITLE
under anything else in application, can we say 500 characters including spaces?

### ISSUE THREAD

**Issue by sarahsaltiel** [usds/website#337]
We've had issues with applications disappearing because of applicants going over the character count (bc they assume it doesn't include spaces). Can we change the text to be obvious?

Current:
Optional. Tell us about problems you would like to solve, areas you are passionate about, or why you would like to join. Limit: 500 characters.

Updated:
Optional. Tell us about problems you would like to solve, areas you are passionate about, or why you would like to join. Limit: 500 characters including spaces.

I would do it myself but I can't find the code to edit.

**Comment by nacingov** [comment]
I'm curious, have we received reports of people specifically thinking that they assumed spaces didn't count?

**Comment by nacin** [comment]
@jas298 Do you have the ability in Salesforce to modify the HTML of a form control, and if so, can you add the `maxlength` attribute to the `textarea`? It should look probably something like this:

`<textarea id="appPage:appForm:whyJoin" name="appPage:appForm:whyJoin" title="Why do you want to join the United States Digital Service?" type="text"></textarea>`

Then change it to:

`<textarea id="appPage:appForm:whyJoin" name="appPage:appForm:whyJoin" title="Why do you want to join the United States Digital Service?" type="text" maxlength="500"></textarea>`

This works in all modern browsers (incl. IE10+) and should significantly limit our woes.

If it's some weird markup language, happy to help figure out how to get a `maxlength` attribute in there.

**Comment by sarahsaltiel** [comment]
@nacin yes - and unfortunately a lot of folks don't know they did it wrong. They just submit an app and don't receive a confirmation or have the application go anywhere.

**Comment by jas298** [comment]
@nacin @nacingov Salesforce is giving me an error saying that "maxlength" is an unsupported attribute, so I did a little Googling and discovered... https://success.salesforce.com/ideaView?id=087300000007SBuAAM. As far as I can tell, this feature has not been implemented, and there is no way to restrict length in visualforce (the language this is written in) until the person hits "submit" (see also https://developer.salesforce.com/docs/atlas.en-us.pages.meta/pages/pages_compref_inputTextarea.htm). 

So, I think a javascript work around is the best idea here (and then also fixing the styling issues we're having with the error page). Is that possible? See also #224 in case that is helpful.

**Comment by jaredcunha-usds** [comment]
Addressed now in new form that will be posted soon. The number shows characters remaining and counts down as user types.
