### ISSUE TITLE
VISA APPLICATION ACCOUNT PAGE

### ISSUE THREAD

**Issue by rdinion** [usds/website#346]
https://cgifederal.secure.force.com/updatedata
When navigating through the series of pages on this page the user should not constantly have to go through each page to get to step they need to enter data on or perform.
The bread crumbs along the top should show for any step the user has already performed and there is data in the database to populate the page.

**Comment by jas298** [comment]
@rdinion The State Department runs the visa application payment system. This is not the right place for support; please contact your local consulate. The consulate in Minsk has a website at https://by.usembassy.gov/ and their email address is consularminsk@state.gov.
