### ISSUE TITLE
Add link to /us-digital-service from the /apply page

### ISSUE THREAD

**Issue by mollieru** [usds/website#35]
@kathytpham let's figure this out together

**Comment by kathytpham** [comment]
Ok! Is this for the submit button? If you send me the link, I'll get it to
redirect.

On Fri, Jan 23, 2015 at 10:48 AM, mollieru <notifications@github.com> wrote:

> @kathytpham <https://github.com/kathytpham> let's figure this out together
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhiteHouse/usds-website/issues/35>.
>



-- 
912-220-6423
kathytpham@gmail.com
