### ISSUE TITLE
Where is the "Contribute idea/s on what USDS should make more available to the public"?

### ISSUE THREAD

**Issue by RWinDC** [usds/website#363]
Currently, the US Department of Agriculture, National Science Foundation, DoD, et al., spend federal dollars on research: where is there a DIGITAL repository of proposal abstracts and reports submitted by the principal investigators on their results?  E.g., I was interested in the Analog Forestry underlying a USAID/USDA project yet the proposal was only available (to read but not retain) in hard copy at the National Agricultural Library; none of the reports (annual/final) were available and the website the grantee posted is now defunct.  So, in summation, here's a > $500K project spent in the early nineties and almost all evidence (reusable research) is missing; this is one exemplar of this unfortunate reality.  Finally, if USDS is supposed to be an example of making Government more responsive, where is the "What Project/s Should We Pursue" button/contribute ideas area?

**Comment by jaredcunha-usds** [comment]
Thank you for the feedback!
