### ISSUE TITLE
Security Cooperation Information Portal

### ISSUE THREAD

**Issue by Eric7084** [usds/website#368]
USDS,
I am a military member who works for a US Embassy coordinating Foreign Military Sales projects for the partner nation.  The United States contributes millions of dollars each year to the particular country I work in and to many other countries throughout the world.  All of our projects are managed on a website called the Security Cooperation Information Portal (SCIP).  This website could use some serious updating to allow users like myself to navigate all the projects we fund for our partners.  As well, the partner nations utilize this website and imagine if it is difficult for a US person to utilize the website, it would be very difficult for a foreign partner to utilize when english is not their first language.  Although this may not be a high priority for the USDS right now, it might be worth taking a look at.  If you need more information from myself, feel free to contact me at my email address.
Regards,
Eric
P.S. I heard about your organization through the Mr. Money Mustache Blog.

**Comment by jaredcunha-usds** [comment]
Thank you for the feedback! Unfortunately, we will not be hosting our content in multiple languages at this time.
