### ISSUE TITLE
Set resize="none" on [Join Us] textarea

### ISSUE THREAD

**Issue by jrpool** [usds/website#371]
Cf. issue #224, but this is a different issue. If the textarea is near the bottom of the window and the user enlarges it vertically to make all of its multiline content simultaneously visible, the user may be unaware that by enlarging the textarea he or she is moving the bottom of the iframe form beyond the bottom edge of the fixed-size iframe. When the user scrolls the page in the window to finish completing the form, it can then appear that the Submit button does not exist, because the iframe form has no scroll bar even if it is too deep for its container. One solution is to set resize="none" in the inline style of the textarea element in the source file containing the form.

An example of such an apparently missing Submit button is attached. This actually happened to me while I completed the form, and I was unaware of the existence of the invisible Submit button.
![usdsbug2](https://user-images.githubusercontent.com/3364797/35957891-bafa497c-0c52-11e8-81f8-62509f4e5b93.png)

**Comment by jaredcunha-usds** [comment]
I've verified this issue on my end. If the user drags the handle below the iframe boundary, it is impossible to recover and the user will need to start over. 

![screen recording 2018-03-19 at 02 46 pm](https://user-images.githubusercontent.com/25435289/37616070-2dc92b84-2b85-11e8-803b-277645b81404.gif)

I don't have access to the iframe. @nacingov, do you know who does? Applying a `max-height` to the `textarea` would also address the issue.

**Comment by jaredcunha-usds** [comment]
We have a new form that be available soon where this issue has been addressed.
