### ISSUE TITLE
broken email address?

### ISSUE THREAD

**Issue by ktarbet** [usds/website#373]
Steps to reproduce: 
Send an email to the address: usds@omb.eop.gov as listed in https://www.usds.gov/join 

Result:
in a few days a  "Delivery Status Notification (Failure)" response comes back via email.

```
Final-Recipient: rfc822;USDS@pitc.gov
Action: failed
Status: 5.0.0 (permanent failure)
Diagnostic-Code: smtp; 5.4.7 - Delivery expired (message too old) 'timeout' (delivery attempts: 0)
```

Expected Result: 
Either nothing or preferably a human reply.

**Comment by jaredcunha-usds** [comment]
Hi, I believe this issue is resolved. Closing.
