### ISSUE TITLE
No submit button on chrome

### ISSUE THREAD

**Issue by sobopla** [usds/website#378]
After filling out the form, there is not an option to submit the form on Chrome Browser, Mac OS.

**Comment by sobopla** [comment]
![screenshot 2018-09-04 14 53 01](https://user-images.githubusercontent.com/19863639/45054360-52566280-b052-11e8-93ba-0b9fbc9abee8.png)

**Comment by jaredcunha-usds** [comment]
Hi Catherine - This was likely addressed a while back but we never closed the issue. We'll have a new form coming out that should prevent the button from being cut off by the iframe's height in the future.
