### ISSUE TITLE
Instructions for Rookies link broken on the ReadMe.md

### ISSUE THREAD

**Issue by neilmartis** [usds/website#385]
The rookies hyperlink for "Instructions for rookies learning how to edit the website can be found here." is broken. File name - website-instructions.md file is missing

**Comment by jaredcunha-usds** [comment]
@neilmartis - Were you referring to these links? 

<img width="956" alt="screen shot 2019-02-27 at 9 52 04 am" src="https://user-images.githubusercontent.com/25435289/53498988-6dd87e00-3a75-11e9-98f4-1089bc7d93b6.png">

I just updated the README to fix those links. Please let me know if anything else was missed. We were did most of our development in another repository, so some of those links might have been missed in the process of bringing everything over.

**Comment by neilmartis** [comment]
@jaredcunha-usds  Hi Jared actually I was referring to web contribution guidelines link which is there in the readme file so a newbie can contribute to the codebase. This hyperlink was in the readme in the old website readme

**Comment by jaredcunha-usds** [comment]
Oh, okay. I'm going to rewriting much of that content that explains how to edit, so that page is not going to be very relevant right now.

**Comment by neilmartis** [comment]
Thanks @jaredcunha-usds Quick Q is the site built using usds-jekyll gem based on the web design standard??

**Comment by jaredcunha-usds** [comment]
Did you meant the USWDS-jekyll gem? It is not using the gem. The site built with USWDS 2.0, which did not appear to be updated in the gem. 

Would you be okay if I close this issue?
