### ISSUE TITLE
Permalinks have .html - why?

### ISSUE THREAD

**Issue by wslack** [usds/website#391]
# Generic Issue

Why are the permalinks with an .html at the end? The URLs are cleaner without those 

Example .md file with the .html permalink: https://github.com/usds/website/blob/master/_projects/0100_medicare-payment-program.md

Compare:
- https://www.usds.gov/projects/medicare-payment-program.html
 - https://www.usds.gov/projects/medicare-payment-program

**Comment by jaredcunha-usds** [comment]
Oh, that's a really good point!
