### ISSUE TITLE
Add Diversity & Inclusion PDF to the usds.gov footer

### ISSUE THREAD

**Issue by ButtersUSDS** [usds/website#399]
# Site Update

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What would you like to do?

- [ ] Update an existing page/feature
- [ ] Add a new page
- [x] Add a document link to the footer

## How can we help?

Please link to our Diversity & Inclusion PDF in the USDS.gov footer

**Comment by ButtersUSDS** [comment]
[USDS_1Sheet_D&I_Feb2019.pdf](https://github.com/usds/website/files/2911212/USDS_1Sheet_D.I_Feb2019.pdf)

**Comment by jaredcunha-usds** [comment]
@ButtersUSDS 

Can you provide an image of how you would like the link to appear in the footer? Or at the very least, let me know where (ex. Under "Upcoming Events") and what the link text should say?

**Comment by ButtersUSDS** [comment]
@jaredcunha Yes, oops! 

![image](https://user-images.githubusercontent.com/32076293/53505888-cfebb000-3a82-11e9-904e-46e563e33725.png)

**Comment by ButtersUSDS** [comment]
<img width="1024" alt="footer" src="https://user-images.githubusercontent.com/32076293/53506003-117c5b00-3a83-11e9-8bdf-e30b23befb36.png">

**Comment by jaredcunha-usds** [comment]
Added
