### ISSUE TITLE
Update Press 1-Sheet for the Footer link "USDS Press Kit"

### ISSUE THREAD

**Issue by ButtersUSDS** [usds/website#401]
# Site Update

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What would you like to do?

- [x] Update an existing page/feature
- [ ] Add a new page

## How can we help?

Update the Press Sheet PDF with this file: 
[USDS-Press-Sheet.pdf](https://github.com/usds/website/files/2911315/USDS-Press-Sheet.pdf)
This is linked to in 2 places: the footer and the "News & Blog" page (see screenshots below).

## Additional Context

  Add design mock-ups here.
<img width="1009" alt="press kit footer" src="https://user-images.githubusercontent.com/32076293/53506534-25748c80-3a84-11e9-9983-77b546fa1847.png">

![image](https://user-images.githubusercontent.com/32076293/53506451-fe1dbf80-3a83-11e9-81a5-b0ebe72dbce4.png)

**Comment by jaredcunha-usds** [comment]
Merged: https://github.com/usds/website/pull/408
