### ISSUE TITLE
Revision to 'about us' infographic layout

### ISSUE THREAD

**Issue by mollieru** [usds/website#41]
for @nguyenist + @davidrkaufman -- awesome work on this! per request, here's a slightly modified version to make this a little bit shorter and snappier. Removed 1.5 graphics, increased size + line height of typography, modified padding just a bit. This isn't pixel perfect but happy to help it get there as is helpful. as follows:

Type specs: 
Merriweather
size 22px
line-height: 30px

![homepage-infographic-color-mredits-01](https://cloud.githubusercontent.com/assets/3680494/15193066/17df292e-178a-11e6-95ba-a2457a8c6447.png)

**Comment by davidrkaufman** [comment]
@ErieMeyer - Thanks for the feedback. Can you clarify what you mean re: "financial assistance"? The only employee metric we are okay to share is the 50% women stat.

Design Edits @nguyenist --
- Hoodie swap is good
- SBA we can add, but we haven't discussed IRS publicly yet
- Let's change the pie chart to just be a 50/50 split and the copy will read "50% women, 50% men"
