### ISSUE TITLE
Create a page that lists all articles with USDS in the news

### ISSUE THREAD

**Issue by jaredcunha-usds** [usds/website#410]
# Site Update
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What would you like to do?
- [x] Update an existing page/feature
- [x] Add a new page

## Idea

We might want to have a page that archives all press articles with USDS in the news. Right now, the homepage and the News & Blog page contain the set of news articles, capped at 9. Do we want to have a page that is essentially a bulleted that would capture everything in https://github.com/usds/website/blob/master/_content/news_articles.yml ?

We might also want to explore how we can differentiate the list of in the press articles on the homepage from the news & blog page.

**Comment by kategreenUSDS** [comment]
looks like this page has been created since this ticket was written.

https://github.com/usds/website/blob/master/_content/news_and_blog.yml
