### ISSUE TITLE
Update Vets.gov screenshot. 

### ISSUE THREAD

**Issue by dannychapman** [usds/website#42]
![work-imgs-veteras-new](https://cloud.githubusercontent.com/assets/281709/9616513/8d617ef2-50cc-11e5-9666-b9e95dd30ce3.png)

**Comment by mollieru** [comment]
@dannychapman or @emilyville could I get an update of an image you'd like us to use from the live site?

**Comment by dannychapman** [comment]
![vets-screenshot](https://cloud.githubusercontent.com/assets/281709/12065083/13ee5b26-af9f-11e5-9081-988eb04cf057.png)

@mollieru Here you go!
