### ISSUE TITLE
Explore getting a staging environment

### ISSUE THREAD

**Issue by jaredcunha-usds** [usds/website#442]
Explore setting up a staging environment for usds.gov. It would be nice to get staging.usds.gov so content editors can preview what updates will look like on the website to ensure quality and correct mistakes.

**How it could work**
- Commits to `master` are deployed to staging.usds.gov automatically. 
- USDS.gov prod builds every 24 hours

**Questions**
- What can we use for deployment scripts?
- What can we use for any necessary testing?

**Comment by drew-usds** [comment]
**[Federalist](https://federalist.18f.gov/)**

**[Cloud.gov](https://cloud.gov)**
Set up a sandbox account to watch a `staging` branch? Is there a general USDS account so it's not locked to an individual?

**[Netlify](https://www.netlify.com/) ([Netlify docs](https://docs.netlify.com/configure-builds/repo-permissions-linking/#git-provider-permissions) | [Setup example](https://eduardoboucas.com/blog/2017/02/22/jekyll-staging-environment.html))**
Is this cleared for us to use? We'd likely need the Pro tier at $45/month so it's not locked to a single user. Or we share the login/pass for a single account?

**Set up separate staging repo**
Push local changes to website-staging repo, push changes to main repo to deploy. Could cause base url issues, and maintaining two repos could get sticky.

**Comment by drew-usds** [comment]
HUGE kudos to @peterwaterman and @lisac-usds! We tested the following at the hackathon:

- Sandbox environment using cloud.gov -- can be used for setting up/sharing larger feature changes that may not be close enough to release for a PR.
- Netlify GitHub add-on -- automates builds per pull request. Can give .md/content editors an option for preview/review without having a full dev environment on their machine.

Todo 3/6:

- [x] Set up cloud.gov sandbox connected to new branch
- [x] Move Netlify app to production repo
- [x] Add environment indicator for staging/sandbox
 - [ ] ~Look into Netlify oauth for users/groups~
 - [x] look into custom netlify build url
 - [ ] ~add Netlify status badge to readme?~
- [x] Document setup/gotchas of each in readme.

**Comment by pete-gov** [comment]
Branch created with staticfile and build manifest. https://github.com/usds/website/tree/cloud.gov

**Comment by lisac-usds** [comment]
possible instructions for linking staging.usds.gov to netlify: [Configure external DNS](https://docs.netlify.com/domains-https/custom-domains/configure-external-dns/)

**Comment by drew-usds** [comment]
Closed in #510
