### ISSUE TITLE
Update project and people carousels

### ISSUE THREAD

**Issue by jaredcunha-usds** [usds/website#447]
There are lots of items in a carousel. Try to limit to 3 or 4 pages and add a VIEW ALL as a last card. This applies to both people and projects.

The VIEW ALL card needs visual design.

-----

**Overall**
- [x] Limit number of cards on carousels. 6 for projects (there are 7 projects, it'd leave an awkward, mostly empty group with 9). 9 for profiles (shows a decent number without getting out of control on mobile).
- [x] ~~Add VIEW ALL last cards on carousels~~ People/project carousels already have a "see all" button as part of the component.

**People**
- [x] Move carousel into includes
- [x] Add "alumni" tag to person card (from 1/8/20 website meeting)
- [x] ~~Add "alumni" tag to person front matter~~ Already present
- [x] Add people carousel to bottom of person show page
- [x] Randomize show order. Will only be random per site build (testing to see if that helps views of other profiles)
- [x] DRY up carousel includes/people data yml
- [x] Update alumni status
- [x] Fix typo in Kasia Chimielinski -> [Kasia Chmielinski](https://www.linkedin.com/in/kchmielinski) + add redirect

**Comment by drew-usds** [comment]
Current work is in 🌿`carousel-update`.

**Comment by drew-usds** [comment]
Closed in #497
