### ISSUE TITLE
Minor layout issue in presidential greetings request. Is this the right repo?

### ISSUE THREAD

**Issue by anselmbradford** [usds/website#45]
Does USDS control `whitehouse.gov/contact/presidential-greetings-request`?

`.textcaptcha-challenge-description` needs `background-position: left` set for Challenge Question star:

![screen shot 2016-03-09 at 9 14 11 pm](https://cloud.githubusercontent.com/assets/704760/13657294/1f7993a6-e63c-11e5-9ac2-77ba2a832c78.png)

(Aside: captcha text reads kind of strange in some cases.)

**Comment by alex** [comment]
USDS is not involved in running that page, I'm not sure where the right place to file that issue would be unfortunately.

**Comment by anselmbradford** [comment]
https://github.com/WhiteHouse/fortyfour perhaps? Petitions also has the same class, but not the bg image https://github.com/WhiteHouse/petitions/blob/1a4ccb0307c5281e03fdd2828d379b4087498666/modules/custom/wh_core/wh_core.css#L310

**Comment by anselmbradford** [comment]
Moved to https://github.com/WhiteHouse/fortyfour/issues/22 ... looks to be in the styles for the Drupal textcaptcha module. Thanks for the quick input @alex !
