### ISSUE TITLE
Design an Agency Team Page Template

### ISSUE THREAD

**Issue by ButtersUSDS** [usds/website#450]
### Problem
As shown in the [Usability Test Report](https://github.com/usds/ux/blob/master/projects/USDS%20website%202019/USDS.gov%20Usability%20Test%20Report%20FINAL.pdf), users are confused about the relationship between USDS and agencies. 

### Requirements
- Design should be templated, such that content is analogous across agency pages (or page sections)
- The content should emphasize the work done at respective agencies and the constituencies helped by those agencies
- The content should not focus on sub branding or team sub culture (since we are a Branded House—one team, one mission)
- There should be an overt explanation of the relationship of agencies to USDS and how staff is allocated to each

### Next Steps
- [ ] Research what agency specific content would be useful to users
- [ ] Design straw man agency pages (or single scrolling page with sections)
- [ ] Determine the most natural flow for users to discover this site section and amend IA accordingly
- [ ] Build template
- [ ] Collect content

**Comment by LauraUSDS** [comment]
Closing as we do not currently use the structured agency team model
