### ISSUE TITLE
Fix hyperlink color for news article links

### ISSUE THREAD

**Issue by LauraUSDS** [usds/website#457]
# Bug Report
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened
Hyperlinks for our news/press articles are showing bright blue instead of USDS blue. It's happening on both the homepage and on the press page.
<img width="1087" alt="hyperlink-screenshot" src="https://user-images.githubusercontent.com/41635635/57405023-676c2e00-71ab-11e9-8738-b16b6b716590.png">

## What I expected to happen
They should be USDS blue :)

## Reproducing
- Device: MacBook
- Browser: Chrome
- Link to page where bug occurred: [homepage](https://www.usds.gov/) and [news page](https://www.usds.gov/news-and-blog)

**Comment by jaredcunha-usds** [comment]
Fixed: https://github.com/usds/website/pull/458
