### ISSUE TITLE
Old Instagram API deprecated. Find replacement. 

### ISSUE THREAD

**Issue by jaredcunha-usds** [usds/website#464]
Instagram accelerated deprecation of their API, so we can no longer use the script we were using to pull images from our instagram feed. 

Instagram is now using the [Instagram Graph API](https://developers.facebook.com/docs/instagram-api), so we will have to use that. 

@dmethvin-gov Any chance you want to look into this if you have time?

**Comment by dmethvin-gov** [comment]
What does the timeline look like for this? It would be fun to investigate but it may be a week or two.

**Comment by jaredcunha-usds** [comment]
I don't think the world is going end if it takes us some time.

**Comment by dmethvin-gov** [comment]
@jaredcunha Looking at this today, I'll leave notes here.

Our current IG setup is in [instagram.js](https://github.com/usds/website/blob/c26b80900fe8ec37c6c790709f7f5b081d7e727a/assets/js/site/instagram.js) and looks to have been built with someone's personal account number. The new API doesn't allow that.

The Instagram Graph API requires an [Instagram Business Account](https://help.instagram.com/502981923235522) or [Instagram Creator Account](https://help.instagram.com/1158274571010880), do we have either of those? Who would know? I'll ask on Slack. Those IG setups have to be linked to a Facebook account (and not a personal one).

From what I can gather the User of the IG account needs to create an IG Media Album and we need to put any photos that we want in the front-page carousel into that. [These are the API instructions](https://developers.facebook.com/docs/instagram-api/reference/media/children) but I'm not sure of the create/authorize part that has to be done and what steps it takes to put photos in that album.

The best explanation I've found so far is [this personal blog post](https://bernardodiasdacruz.com/2018/03/05/fetching-from-instagram-using-facebook-graph-api/) which points out it's no longer possible to fetch photos via exclusively client-side code. We'll need to rewrite it to have the photos pulled by the server, or run some occasional job to update them somehow.

**Comment by dmethvin-gov** [comment]
Facebook hasn't answered us yet to "approve" our "app". There's no particular reason that we should need their permission to display our own Instagram photos so I've gone back to good old screen scraping. There's a JSON payload in the HTML page that has everything we need.
