### ISSUE TITLE
Remove extra space from bottom of /apply

### ISSUE THREAD

**Issue by drew-usds** [usds/website#481]
Looks like there's a ton of extra space below the submit for the /apply form.

![localhost_4000_apply](https://user-images.githubusercontent.com/57154955/71588626-2c2ebe80-2af0-11ea-9df0-dde445737eb7.png)

The iframe from Salesforce is set at 3600px high on the layout ...

```
<iframe src="https://wh45.secure.force.com/digitalserviceform" seamless width="100%" height="3600px" scrolling="no" frameBorder="0" title="Join USDS form"></iframe>
```

Todo ->

- [ ] Determine the height of the content in the iframe
- [ ] Set the iframe height to that value
- [ ] Make sure this works with larger text sizes/mobile/etc

**Comment by LauraUSDS** [comment]
@lisac-usds This is another USDS website thing that could benefit from your eyes, since you have access to both the website and Salesforce...any ideas on how to fix?

**Comment by lisac-usds** [comment]
some progress! I'm thinking this could be a 2-part fix, part 1 in #547; part 2 would be to remove the debug (`isTestingMode`) part of #547.  I'll circle back in a week.

**Comment by drew-usds** [comment]
@lisac-usds @laura-usds I did some YOLO-merge testing late tonight since the only way we can see this work is on the live site and I didn't want to interfere with someone actively applying ... and ... well ... Lisa's additions in #547 work! So ... this is live _now_.

**I turned off testing mode and it looks to be working across browsers/devices**.

Tested and working on:

- MacOS - Chrome, Safari, Firefox
- Windows 10 - Chrome, Edge
- iOS (phone and tablet) - Safari, Chrome, Firefox

Not tested:

- Android

**Small things to note:**

- I didn't use Lisa's PR fork because I had other changes to apply to related CSS and JS I wanted to test as well. But it's the same JS from #547 .
- Issue with app-wide JS/this change is just a script tag on `apply.html`. If added to `application.js` it breaks a few things. Definitely some pilot error on my part and should be cleaned up.
- Issue with screen resizing: if you swap from portrait to landscape view on mobile or scale down a desktop window significantly, the height of the iframe doesn't change. You can still continue to scroll down to the submit button, but we should add JS to watch for window resize.

**Comment by pete-gov** [comment]
![Screenshot_20200828-134416](https://user-images.githubusercontent.com/51794651/91599931-11d60a80-e935-11ea-801d-e59527c7f46a.png)
![Screenshot_20200828-134443](https://user-images.githubusercontent.com/51794651/91599936-139fce00-e935-11ea-8725-584cc8693c3c.png)

Here's how it renders on my Google Pixel 3 (Android) in Chrome and Firefox Beta.

**Comment by LauraUSDS** [comment]
@drew-usds I asked Pete to check it on his Android (see screenshots above), and I think it's a vast improvement. Closing this issue 🙌
