### ISSUE TITLE
Nav centerpiece click area issue

### ISSUE THREAD

**Issue by thecristen** [usds/website#49]
The `#logo-desktop-full` link in `li.nav-centerpiece`, while at `opacity: 0`, still creates an awkwardly large click area that interferes with filling out form fields.

![image](https://cloud.githubusercontent.com/assets/2136286/15508616/2efdaa90-219e-11e6-927d-cc2f0f231461.png)

Chrome on Mac OS X.

**Comment by cew821** [comment]
Thanks so much for reporting this; working on fix now.

**Comment by cew821** [comment]
This fix was deployed a few days ago. Thanks again to @thecristen for reporting
