### ISSUE TITLE
Playbook: Add USDS.gov analytics tag

### ISSUE THREAD

**Issue by melissajschaff** [usds/website#498]
It would seem that playbook.cio.gov is no longer collecting analytics on GA. Let's add it to USDS's GA account and start capturing info there. There are 2 options: we can 1) add the same tag as USDS.gov or 2) (preferred) create a new property and give it its own UA tag on USDS.gov's analytics account. Either way, it should should have some tracking on it, since it fell off the cliff in Nov 2018...

@drew-usds lets collab on this.

**Comment by drew-usds** [comment]
@melissajschaff option 2 sounds good! I've got a few commits going into a Playbook PR this week and can roll this into it. Can you create the new property/UA tag and copy/paste the JS in here?

**Comment by melissajschaff** [comment]
this should be what you need....you should also have rights to view this in the GA admin panel

Tracking ID: `UA-132706295-2`
Global Site Tag (gtag.js):
```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-132706295-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-132706295-2');
</script>
```

**Comment by drew-usds** [comment]
@melissajschaff Looks like there's already some _older_ GA stuff here with DAP ...

> https://github.com/usds/playbook/blob/gh-pages/assets/js/federated-analytics.all.min.js

Does our own GA account supersede the DAP one, or does the existing one feed into other reporting I don't know about? I don't think you're supposed to have both old and new tracking going at the same time on principle, but they should theoretically work side-by-side.

👆Edit: Duh, in your description you mention that the original tag isn't collecting anything we can see presently. Just not sure if the old one is connected to other DAP things. We can have them run together for a bit and check in to see how they're doing (will make a follow-up issue).

**Comment by melissajschaff** [comment]
1. our GA account is newer than and independent from the DAP account. They do not feed into the same reporting view and probably never will, unless _we_ make that call. 
2. I tried to find recent traffic for playbook.cio.gov in DAP's reporting view (the Federal-wide analytics account, which I believe you also have access to) and while I did find it, traffic ends 2/2018 and it's unclear why. There is a comment left in GA from DAP on 2/6/2018
> Added new filter on 2/6/18. Please contact dap@support.digitalgov.gov with any questions. freddie.blicher@gsa.gov
3. You can have multiple tags tracking on a site, but IMO since the DAP tag isn't doing anything and doesn't seem to have been collecting anything since 2/2018, I think we should switch it out for ours, right?

To recreate what I saw:
> 1. select the Government-Wide Account
> 2. Government-Wide 360 property (UA-33523145-1)
> 3. Find the the Executive Office of the President view (66351974)
> 4. Under Reports, expand Behavior, Site Content, go to All Pages
> 5. In the date selector, filter back to sometime in 2016 (I went back to 12/1/2016 - today)
> 6. Once it refreshes the data, search `playbook.cio.gov` at the bottom right where the pages display and it will take a second, but you will see the data refresh

Edit: just saw your 👆 edit post-posting. I'm not sure what, if any, impact there will be if we straight up remove DAP's tag from the playbook site. I mean, nothing is being collected, so it's basically a 👻 to them 🤷‍♀

**Comment by drew-usds** [comment]
Closed in [playbook/231](https://github.com/usds/playbook/pull/231).
