### ISSUE TITLE
TechFAR Hub: update USDS branding in footer

### ISSUE THREAD

**Issue by drew-usds** [usds/website#506]
- [ ] Update old logo in the footer.

<img width="1258" alt="Screen Shot 2020-02-27 at 11 38 45 AM" src="https://user-images.githubusercontent.com/57154955/75465067-1bff5800-5956-11ea-80d7-846514742e19.png">

**Comment by LauraUSDS** [comment]
completed in https://github.com/usds/usds/issues/5634
