### ISSUE TITLE
Update D&I PDF file

### ISSUE THREAD

**Issue by LauraUSDS** [usds/website#509]
Replace old Diversity & Inclusion report (Nov 2019) with new report (March 2020). 

Needs to be live by March 9th. 

I believe the file lives here: https://github.com/usds/website/tree/master/assets/files

**Comment by LauraUSDS** [comment]
@drew-usds I should be able to replace the existing file in the GH folder I mention above and that will update the PDF, right? Unless I'm missing something (always a possiblity). 

Also...can you tell if the recruiting 1-sheet in that folder is actually linked to anywhere on the website? If so, it's old and I'd like to replace it too (we can re-name with something more generic, like the d&i report, to prevent future code changes).

**Comment by drew-usds** [comment]
@LauraUSDS yes, if you replace the existing file with a new thing with the exact same file name, it will update. 

I did a search for the recruiting one sheet filename and don't see it linked to from anywhere on the website, so if it's out of date we can remove it (I can't speak for anywhere _else_ on the interwebs it may have been linked from though).

**Comment by LauraUSDS** [comment]
Done. Editable files are in the branding repo (for future reference): https://github.com/usds/branding/tree/master/One-Sheets/USDS_Diversity%2BInclusion/2020-03%20Diversity-and-Inclusion
