### ISSUE TITLE
fix capitalization of headers on privacy page

### ISSUE THREAD

**Issue by LauraUSDS** [usds/website#517]
Headers should be Sentence case (not Title Case)
https://www.usds.gov/privacy

**Comment by drew-usds** [comment]
Also found/fixed other sentence case issues in headers on the following:

- [x] Navigation
- [x] Footer
- [x] Events (it's redirected currently, but still)
- [x] FAQ
- [x] News & blog
- [x] Our mission
- [x] Contact us
- [x] How we work
- [x] Mission
- [x] People
- [x] Projects

**Comment by drew-usds** [comment]
Rolling this into [PR 515](https://github.com/usds/website/pull/515).
