### ISSUE TITLE
change values description

### ISSUE THREAD

**Issue by LauraUSDS** [usds/website#519]
Edit text for the description of our "Go where the work is" value to:
> Meeting with civil servants where they are means we can partner to create lasting change. Modernizing government is up to all of us, together.

It appears on this page: https://www.usds.gov/mission

**Comment by LauraUSDS** [comment]
@juliacmoore Added you as an assignee just for FYI (and bc you are keeping tabs on the content development for R2C). @drew-usds can you help us change this language when you have a min?

**Comment by drew-usds** [comment]
Updated and am rolling this into [PR 515](https://github.com/usds/website/pull/515).
