### ISSUE TITLE
/Apply form updates

### ISSUE THREAD

**Issue by drew-usds** [usds/website#524]
[From Slack 4/6/20 w/Tali, Michael, Andrea, Ange](https://usds.slack.com/archives/CD7AT8PGB/p1586198914177600):

- [x] Forms are on Salesforce, website folks need accounts
- [x] Add options/language to form along the lines of "please let us know if you require accommodations or have special needs"
- [x] Add derived preference language to `veteran` option

[From 6.03.20 request in #infra-website Slack channel](https://usds.slack.com/archives/CDGMC1NKF/p1591193448011200):
- [x] make uploading a resume mandatory

- [x] look into why the number of spam apps has gone up recently ([request in #infra-website channel](https://usds.slack.com/archives/CDGMC1NKF/p1591293925014500)). example of a spam app: [#37963](https://eopfra.lightning.force.com/lightning/r/USDS_Application__c/a00t000000FqZMFAA3/view)

[from 06.09.20 testing and user reports]
- [x] review constraints on input fields (is `Last Name must be between 2 and 20 characters.` still appropriate?)
- [x] if you fill out the form but hold off on submitting, say for 30 minutes, and then click Submit.... this might lead to an error page

----

Background:

>Should we add "please let us know if you require accommodations or have special needs" to the interview emails (QC/TQ1/Sprint) or the guide check with candidate at the beginning of the interview journey (I think we should)?

> hi! our application currently asks applicants if they themselves are a veteran, but I've just had someone reach out who is eligible for derived preference (more info on that here! https://www.fedshirevets.gov/job-seekers/veterans-preference/family-member-preference/). can we adjust the wording to make it more clear so that these spouses/parents/widow(er)s are able to check the box for their entitled preference as well?

> the talent team has a request concerning the application page. We've seen a surge of applicants who submit applications with no resumes. It was easier to handle with lower volumes, but its becoming a bit unwieldy. Can we made uploading a resume through the upload link mandatory?

> We've also been getting a number of spam apps recently. Might be worth doing some sort of check for vulnerabilities

**Comment by mriverasl3** [comment]
No one on our team can currently make the change through Salesforce. Apparently, USDS can grant full Salesforce access to folks to make changes (David Holmes was the last person to make changes in there), but I don't know myself how to do that.

**Comment by lisac-usds** [comment]
I'm really curious about the last two (make uploading a resume mandatory, and look into why the number of spam apps has gone up recently) - planning to take a look tonight.

update (6/5): i didn't get very far, will spend more time over the coming week.

**Comment by LauraUSDS** [comment]
@lisac-usds @mriverasl3  How are we doing on resolving these small outstanding things for the apply form on our website?

**Comment by lisac-usds** [comment]
I'm discouraged on figuring out this one:
> review constraints on input fields (is Last Name must be between 2 and 20 characters. still appropriate?)

It's true that the form will not accept a Last Name outside those bounds - 
![image](https://user-images.githubusercontent.com/31673962/89842468-b38ee680-db43-11ea-9f37-46591f13fe2f.png)

But I haven't been able to track this down in the backend.  

From my end, ok with closing this issue.

**Comment by mriverasl3** [comment]
@LauraUSDS - is this ask still doable? "Add options/language to form along the lines of "please let us know if you require accommodations or have special needs"

**Comment by LauraUSDS** [comment]
@mriverasl3 Yes, should be. Can you confirm a) that's the exact phrasing y'all want and b) where exactly it should go on the apply form? Then I'll have @lisac-usds make the change (she's the only one w/ yaml knowledge + access to Salesforce!).

**Comment by LauraUSDS** [comment]
@lisac-usds I think we're ready to wrap that last remaining item! When you have a chance:
- [x] lowercase 'e' in "Current employer"
- [x] right above the 'submit' button: (if possible) add a space between the check boxes and the texts
- [x] right above the 'submit' button: add period at the end of the first checkbox sentence
- [x] right above the 'submit' button: add an additional checkbox in the middle of the two existing ones, with text ~"I have special needs and will require accommodations.”~ "I’d like to request a reasonable accommodation."

CC @mriverasl3

**Comment by LauraUSDS** [comment]
@lisac-usds Is there a way to check all the questions are the same color text? Either my eyes are playing tricks on me or "where can we find you online?" is darker than the others...

(I am happy to do all this nitpicky checking, if you can point me to which file to review)

**Comment by LauraUSDS** [comment]
@lisac-usds Apologies, I jumped the gun. Please use "I’d like to request a reasonable accommodation." for the new checkbox (corrected comment above as well). Thank you!

**Comment by lisac-usds** [comment]
update: tracked down most of these, am still working out the logic for the reasonable request accommodation. Hoping to have an update 9/15.

**Comment by lisac-usds** [comment]
update: 😠 
still struggling with the reasonable accommodation - running into an issue when rendering the form as an iframe. details in the cross-referenced PR. Will continue investigating later this week.

**Comment by LauraUSDS** [comment]
Since the additional checkbox is still being grumpy, let's do a stopgap solution and just add instructional language. My two recommended options:

1. Add to the 'anything else we should know' description. Suggested language to use that's similar to what we wanted for the checkbox: "Please let us know if you would like to request a reasonable accommodation." This may not be a great solution because then they have less space to write their blurb.

2. Add a the language (in italics?) right above the submit button: "If you would like to request a reasonable accommodation, please let our Talent team know when they reach out." (I'm assuming that's the best how/when for ppl to do that since we can't build it into the form.)

@bernars-usa @drew-usds @mriverasl3  This would be easy to add when y'all are doing the other changes to the apply form next Tuesday. Completely defer to y'all on the final solution, so please feel free to make an executive decision on this.

CC @lisac-usds (so you can check this off your list for now!)

**Comment by mriverasl3** [comment]
@LauraUSDS - I'd go with option 2

**Comment by lisac-usds** [comment]
we got the checkbox working! 
this was a configuration issue. details in the cross-referenced PR.

**Comment by LauraUSDS** [comment]
OMG YAY! Huge kudos to y'all, @lisac-usds and @LisaHwang !  Thanks for giving me an early xmas/hannukah present ;)
