### ISSUE TITLE
Resolve security alerts in uswds-jekyll

### ISSUE THREAD

**Issue by LauraUSDS** [usds/website#526]
There are two open security alerts that need to be addressed: https://github.com/usds/uswds-jekyll/network/alerts.

Drew, I'm hoping this is an easy fix on your end?

**Comment by drew-usds** [comment]
@LauraUSDS good eye on this, I honestly didn't even know this repo existed.

Updated it and fixed the security alerts!

**Comment by LauraUSDS** [comment]
Oh, huh. I only noticed bc I got email notifications for the security alerts.... @drew-usds
