### ISSUE TITLE
update Hiring FAQ 

### ISSUE THREAD

**Issue by lisac-usds** [usds/website#549]
Request to update content on the [Hiring FAQ](https://www.usds.gov/faq):
- **What is required to work from the U.S. Digital Service** suggests that 18F can hire non-citizens for some roles. Correction: they do not currently hire non-citizens.
- **What kind of salary might I make?** notes a range of less than $100,000 to around $160,000. Correction: the upper bound is around $170,000.

Verify changes with the USDS Talent Team.

**Comment by TaliKeren** [comment]
Change answer to Q1 from: 

You need to complete a background check and drug test and be a U.S. citizen.

The background check start with either the SF-86 or SF-85P (sample here from the OPM website, a detailed questionnaire about your personal background and where you’ve lived. This includes drug use. Getting your background check cleared can take several weeks or longer.

For our positions you must be a U.S. citizen. If you are a permanent resident, check out 18F—they can hire non-citizens for some roles—or other civic tech organizations

To: 

You need to complete a background check and drug test and be a U.S. citizen.

The background check starts with either the SF-86 or SF-85P (sample here from the OPM website, a detailed questionnaire about your personal background and where you’ve lived. This includes drug use. Getting your background check cleared can take several weeks or longer.

**Comment by TaliKeren** [comment]
For q2 
change: The salary for digital service experts ranges from less than $100,000 to around $160,000. 
to: The salary for digital service experts ranges from less than $100,000 to around $170,000.

**Comment by lisac-usds** [comment]
thank you, Tali!
