### ISSUE TITLE
Fix text display on 404 page

### ISSUE THREAD

**Issue by LauraUSDS** [usds/website#579]
Text displaying on our 404 page is mis-aligned. Likely just needs some formatting TLC? 

For example: https://www.usds.gov/assets/files/USDS_1Sheet_DI_Feb2019.pdf
![image (1)](https://user-images.githubusercontent.com/41635635/95626363-1e777380-0a48-11eb-9e4a-18508cc96a4b.png)

See [thread on Slack](https://usds.slack.com/archives/CD57K0SUE/p1602268802090300) for reference

**Comment by drew-usds** [comment]
The markup was using `flex` properties that weren't getting interpreted as they should have. I swapped the classes to use uswds grid columns instead.
