### ISSUE TITLE
Comply with DHS Directive 20-01

### ISSUE THREAD

**Issue by LauraUSDS** [usds/website#582]
Comply with [DHS Directive 20-01](https://cyber.dhs.gov/bod/20-01/)

_See convo on Slack ([part 1](https://usds.slack.com/archives/CD486C8EL/p1602269427091100) and [part 2](https://usds.slack.com/archives/CD486C8EL/p1602269579092700)) for more info_

**Required actions**

Within 30 calendar days (Friday, October 2, 2020), update the following at the .gov registrar:
- [x] Add a security contact for each .gov domain you have registered, if you have not already done so
- [x] Update the “Organization” field to reflect the unit within your agency that uses the domain

Within 180 calendar days (Monday, March 1, 2021):
- [x] Publish a vulnerability disclosure policy at the “/vulnerability-disclosure-policy” path of your agency’s primary .gov website.
- [x] All newly launched internet-accessible systems or services must be in scope of your policy.

Within 270 calendar days (Tuesday, June 1, 2021), and every 90 calendar days thereafter:
- [x] The scope of your VDP must increase by at least one internet-accessible system or service until all systems and services are in scope of the policy.

At 2 years (Friday, September 2, 2022):
- [x] All internet-accessible systems or services must be in scope of your policy.

**Comment by boris-ning-usds** [comment]
A template of what DHS CISA may want can be found here - https://cyber.dhs.gov/bod/20-01/vdp-template/.

**Comment by lisac-usds** [comment]
we've published the policy! https://www.usds.gov/vulnerability-disclosure-policy

**Comment by LauraUSDS** [comment]
Dare I ask...are we fully done with this? @lisac-usds I'm guessing you're the best person to ask...

**Comment by lisac-usds** [comment]
yikes - I forgot about this. Thank you, @LauraUSDS .
There's some follow-ups needed. On my mind: figuring out how the vulnerability disclosure policy would apply to  [playbook.cio.gov](https://playbook.cio.gov/) and [techfarhub.cio.gov](https://techfarhub.cio.gov/). I'll investigate.

**Comment by LauraUSDS** [comment]
Oh good, glad I brought it back up again then. 😅  Let us know what you find (or if you need help), @lisac-usds. Do we need to think about the sprint discovery guide site or the smeqa site too?

**Comment by lisac-usds** [comment]
for the sprint discovery guide and smeqa, I think we're covered. from the CISA directive:

> Your policy must be published as a public web page in plain text or HTML at the “/vulnerability-disclosure-policy” path of your agency's primary .gov website.

My takeaway: we satisfy this by having https://www.usds.gov/vulnerability-disclosure-policy ; we do not need a `/vulnerability-disclosure-policy` path on subdomains.
