### ISSUE TITLE
Adding portfolio prompt to additional choices for "Primary field of expertise"

### ISSUE THREAD

**Issue by JPGiordano** [usds/website#586]
Hi!

Currently, when an applicant selects one of the following choices for "What is your primary field of expertise?" ( Content Design/UX Writing, User Experience, and Visual Design) they are given this prompt, instructing/requesting that they upload a portfolio or work samples via link or file. 

![image](https://user-images.githubusercontent.com/50152175/97905624-4c329e00-1d10-11eb-8abe-637fec40e12b.png)

Can we please make it so that this prompt shows when an applicant selects "User Research" and "Content strategy" as well?

**Comment by LauraUSDS** [comment]
Hey @JPGiordano - I don't have the right access and/or knowledge to changes this, so tagging in the two Lisas! @lisac-usds @LisaHwang

**Comment by LisaHwang** [comment]
I'm going to close the issue here and open it up under my salesforce repo!

**Comment by LauraUSDS** [comment]
Thanks @LisaHwang! If you want, next time just lmk and I can transfer it to that repo :)
