### ISSUE TITLE
[Home] use Web Design Standards button styles

### ISSUE THREAD

**Issue by mollieru** [usds/website#62]
The homepage buttons seem to have an arbitrary width and border stroke. Suggest using the button styling of the web design standards:
- ensure button width is no wider than the 3 column gird 
- add weight to border stroke tp 'inset 0 0 0 2px'

our buttons:
![screen shot 2016-05-17 at 4 46 41 pm](https://cloud.githubusercontent.com/assets/3680494/15338688/f58e868e-1c4e-11e6-9da6-43af729f0a90.png)

wds buttons:
![screen shot 2016-05-17 at 4 45 45 pm](https://cloud.githubusercontent.com/assets/3680494/15338691/f721187c-1c4e-11e6-9128-517210131e1f.png)

**Comment by cew821** [comment]
This has already been mostly addressed in production: 

![image](https://cloud.githubusercontent.com/assets/1237498/17264167/320f7922-55b3-11e6-94e4-738ddd2428f4.png)
