### ISSUE TITLE
Add DAP js

### ISSUE THREAD

**Issue by drew-usds** [usds/website#620]
TIL: when you use an analytics code _from_ [DAP](https://digital.gov/guides/dap/) it doesn't actually mean you are participating _in_ DAP. You _also_ have to [add _more_ DAP](https://digital.gov/guides/dap/add-your-site-dap/) to be fully ... DAPped? Also TIL: Looks like DAP was once on the site but [got accidentally removed at some point](https://github.com/usds/website/pull/317). Let's add it back! h/t @wslack for flagging 🤜 🤛 

- [x] Add DAP script to `<head>`
```
<!-- We participate in the US government's analytics program. See the data at analytics.usa.gov. -->
<script async type="text/javascript" src="https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=EOP&amp;sub-agency=USDS" id="_fed_an_ua_tag"></script>
```
- [x] Wrap DAP with `if jekyll.environment == 'production' ` so our staging environments don't show up
- [x] Also do the above for Google Anaytics because _whynotwe'realreadyhere_
- [ ] Make sure gh-pages builds from master with `JEKYLL_ENV=production bundle exec jekyll build`
- [ ] Make sure test builds get `JEKYLL_ENV=staging`

**Comment by drew-usds** [comment]
@lisac-usds I just added you to a [draft PR for this issue](https://github.com/usds/website/pull/621).

An outstanding question you can help with is around setting the right environment variable when building the site. Github pages should _theoretically_ build it with the `production` environment by default, but it'd be nice to make sure that it _definitely, always does_.

Is that something we can set up as an Action? I'm guessing we also want to avoid a 3rd party thing here?

**Comment by lisac-usds** [comment]
> Github pages should _theoretically_ build it with the `production` environment by default, but it'd be nice to make sure that it _definitely, always does_.

still looking into this! I'm on the same page, but haven't been able to track down the code or Github pages documentation stating the `JEKYLL_ENV ` is set to `production`.  Planning to have that, or a code snippet that allows us to enforce it, by the end of the week. 

One thing I'll need to double-check: that the cloud.gov deployment (meant for pre-prod testing, but not our primary means; see [manifest.yml](https://github.com/usds/website/blob/1b716a669689654e200eb1b2398a650b4a87c6ca/manifest.yml) ) knows not to use the `production` flag.

**Comment by drew-usds** [comment]
> One thing I'll need to double-check: that the cloud.gov deployment (meant for pre-prod testing, but not our primary means; see manifest.yml ) knows not to use the production flag.

If you don't specify an environment when running/building the site locally [Jekyll will default to](https://jekyllrb.com/docs/configuration/environments/) `JEKYLL_ENV=development`, which will exclude anything specified to show up in `production`. It "works" if you're then pushing that up to staging/specifying `staging` and then pushing, but yeah also agree making sure it is _always_ getting `staging` would be 💯 .

**Comment by lisac-usds** [comment]
argh. I'm not able to track down the code that would show that the GitHub Pages deployment applies the `JEKYLL_ENV=production`. 
But it's mentioned by others, and I don't have reason to doubt that the GitHub Pages deployment is doing this. 

secondary sources:
https://desiredpersona.com/google-analytics-jekyll/ :
> If you are using Github Pages to build your site, GitHub Pages will automatically set jekyll.environment == 'production' for you. 

https://stackoverflow.com/a/34607628:
> GitHub Pages sets the JEKYLL_ENV to production when you push your source code to GitHub and let GitHub Pages build the site. 

If we wanted to have more visibility and control, we could use a more custom GitHub Action, as described on Jekyll: https://jekyllrb.com/docs/continuous-integration/github-actions/
