### ISSUE TITLE
USDS Mission

### ISSUE THREAD

**Issue by melissajschaff** [usds/website#623]
Content question about https://github.com/usds/website/blob/a6f123c4c165ccefc186176cb5c5f0a2109ca2d9/_content/our_mission.yml#L4

I've always heard our mission as:
> Our mission is to do the greatest good for the greatest number of people in the greatest need 
not what is on L4.

In addition to citing 2 different missions on this page being confusing, saying "American People" excludes the great work done by DHS to serve citizens and non-citizens alike, such as asylum seekers in-county and refugees out-country.

**Comment by LauraUSDS** [comment]
These are persistent issues that we've known about for awhile. Closing this issue, as we are addressing these Qs in our current brand review work.
