### ISSUE TITLE
Instagram footer img hack no longer working

### ISSUE THREAD

**Issue by drew-usds** [usds/website#633]
After putting our our last PR and doing a final QA on the live site, noticed that the hacky way we were pulling our Instagram images into the footer area no longer works.

<img width="935" alt="Screen Shot 2021-07-21 at 11 53 56 PM" src="https://user-images.githubusercontent.com/57154955/126588117-0c638528-3d02-46d1-b5f3-8364227cfe12.png">

@LauraUSDS Since it was kind of hacky to begin with ... should we mess with brining it back? We could just host these images ourselves -- when we post one to Instagram that we also want to show up on the site we could add it in GH as well? We could set it up to do it through the GH web interface pretty easily.

**Comment by LauraUSDS** [comment]
@KamariGuthrie Do you have an opinion on the choices @drew-usds gave us above? My inclination is to keep the website footer clean (no Instagram images) for now, until we have a comms team member doing social media full-time that would have the bandwidth to do the upload-to-GH workflow Drew mentioned. Pics are nice, but a manageable team bandwidth is nicer :) 

Third option would be to add a set of static images that never change.

**Comment by KamariGuthrie** [comment]
@LauraUSDS Agree completely. My preference is to not drive folks there until we can finalize strategy with a new hire on staff.

**Comment by LauraUSDS** [comment]
ALright @drew-usds sounds like we can let this sit for now. Really appreciate the flag!!
