### ISSUE TITLE
[Join us] type styling tweaks 

### ISSUE THREAD

**Issue by mollieru** [usds/website#71]
The text on the [Join us] pages isn't looking entirely resolved, so played around to try to get it a bit cleaner.  

Some suggestions:
- Change H1s to H3s (h1 seemed really really large for the space)
- add padding so that top of header text aligns with top of sidenav 
- increase body line height to `line-height: 1.75em`
- wrap body text into `usa-width-five-sixths` 

Here are a few snap of what this would look like:

![screen shot 2016-05-17 at 7 09 34 pm](https://cloud.githubusercontent.com/assets/3680494/15342429/0fb190e2-1c63-11e6-9734-c9d8cb257c78.png)

![screen shot 2016-05-17 at 7 08 43 pm](https://cloud.githubusercontent.com/assets/3680494/15342432/182f5d62-1c63-11e6-8c1e-9fcb7597a2a2.png)

**Comment by davidchang-gov** [comment]
I think the concerns here were addressed. Closing. Thanks!
