### ISSUE TITLE
add the ability to create new pages or sections of the website

### ISSUE THREAD

**Issue by kategreenUSDS** [usds/website#761]
"I can edit existing content but I can't create something new."
"I like to be self-sufficient, I don't want to bother people to do my job."

Making a method to add new pages or sections will allow more independence for content creators. 

TODO: more details, but we need to do discovery

Source: intro meeting and meeting with Alison

**Comment by kategreenUSDS** [comment]
video and audio requested

**Comment by kategreenUSDS** [comment]
Currently this process is:

1. Create new blank page in `pages/`
2. Set up front matter
3. If you wanna make the page a template, create `yaml` structure and files in `_content/`
4. Write `html`

**Comment by kategreenUSDS** [comment]
the "write `html`" step is the big blocker for me. we don't have a default "new page" layout.

solutions could be:
* have a "new page" template that comms could rename. two templates identified: banner and non-banner
* Matt's gh action to generate new pages instead of copying the file over

**Comment by SteveMattinglyUSDS** [comment]
@kategreenUSDS Can you clarify what "section" means here? Section of the site, like people/projects? Section of a page?
Thanks.

**Comment by SteveMattinglyUSDS** [comment]
It's not truly necessary to write html to create a new page. Just create a new `.md` file in the `pages` folder, and it will deploy with any markdown formatting rendered to html. It looks pretty good; the standard site headings and footers, etc are there. The only glaring issue is that there is zero left margin. I am working to address that.
