### ISSUE TITLE
Create gh action to rollback most recent deployment

### ISSUE THREAD

**Issue by kategreenUSDS** [usds/website#777]
We want to create a rollback gh action. It should _probably_ create a branch of the existing site whenhttps://pitc.zoomgov.com/j/16070644870?pwd=Mzlla2NkMzUyUnJ6NHJlOU1DWDVqUT09

- [ ] think through the triggers for this action (is it a merge to master?)

**Comment by SteveMattinglyUSDS** [comment]
I now have a "real" Action that builds and deploys to GH Pages. When activated manually, it prompts for a commit SHA or branch name to deploy (defaults to `master`). This gives us the technical ability to deploy anything that we want from the repo history.

@kategreenUSDS  That may not be an acceptable UX for non-engineers. If not, let's discuss what would be acceptable.

**Comment by SteveMattinglyUSDS** [comment]
This was addressed with the same PR that deploys based on published Releases.
