### ISSUE TITLE
[Deployment] Address cert issue and figure out deployment plan

### ISSUE THREAD

**Issue by cew821** [usds/website#79]
I wanted to kick off a thread about the deployment plan for USDS.gov. Tagging @nacin and @alex who have some interest / experience in this as well.

I think there a few options that I know of:
1. Host on Github Pages, proxy traffic through Max.gov (they can do HTTPS). This is how the Playbook works now, but Max.gov is not super reliable. Still it works and there is precedent.
2. Use the same approach for hosting as OMB uses for other CIO sites, such as: https://management.cio.gov/, and https://https.cio.gov/  - I think @alex knows the details of what was done here. It's possible it is the same as 1?
3. Set up something new for us. Possibly use cloudflare free tier to handle HTTPS, Route53 for DNS and host on Github Pages.
4. Use an 18F set of tools to handle deployment to S3 upon change to the repo via webhooks. This is in the https://federalist.18f.gov/ universe of tools (though we'd just be using the deployment part of federalist for now). 

Curious to get @alex and @nacin to provide more info on how we have done option 2 as that seems the best to me (and we could move the Playbook to match whatever we choose).

Also happy to hear if @chrisfrommann has a different option than one I have listed above.

I definitely don't think we should do the switchover until we have the HTTPS issue sorted.

**Comment by chrisfrommann** [comment]
As a note, per @nacin's suggestion, I ended up using option 3: basically Github pages and Cloudflare.
