### ISSUE TITLE
Update "field of expertise" menu on apply page

### ISSUE THREAD

**Issue by amwhitty** [usds/website#840]
I worked with CoP directors to revise the list of dropdown choices for "What is your primary field of expertise?" on the apply page. I don't have access to salesforce to edit these. This is the revised list:

* Accessibility 
* Administrative Support
* Communications
* Content Design/UX writing
* Content Strategy
* Data Science
* DEIA
* Information Technology (internal)
* Information Technology (policy)
* Operations (delivery)
* Operations (government/financial)
* Procurement/Acquisition
* Product Lawyer
* Product Management
* Site Reliability/Production Engineering
* Software Engineering
* Talent Acquisition
* Talent Management 
* User Experience
* User Research
* Visual Design
* Other

**Comment by JustinAllisonUSDS** [comment]
@amwhitty tracking this https://github.com/usds/Salesforce/issues/239 as well - will try to update this when access is sorted.  Thanks!

**Comment by JustinAllisonUSDS** [comment]
@amwhitty  We are working on this requirement now (finally got access!)  There are some options that you have removed from the original list - should those remain (list below) and if not, what of the new values above should we replace them with?  For example, records with 'Talent Management' should now be 'Talent Operations'...  ?

List of prior fields that are not in your selection above:
-Front End Web Development
-Recruiter
-Security
-Talent Operations

Lastly, during the application process, someone from USDS translates what was provided above on the original application to a new field 'Subject Matter Track' (which is fairly correlated to CoP).  Was there any discussion on modifying that list as well?  For reference, below is the current value set:

Comms/Content
Data Science
Design
Engineering
Executive
Front End Development
Operations
Other
Procurement
Product
Product Lawyer
Strategy & Operations
Talent
Team Lead
SADel

@LisaHwang FYSA

**Comment by amwhitty** [comment]
@JustinAllisonUSDS Thanks for the update! sorry for delay, we have a CoP on-site this week.
Please use the list from 5/23 as the final list, that was editing out and added to. 
items not on my list should be removed entirely. 

I did not know about the subject matter track, so it has not been modified. Do you need to know how the primary fields of expertise map to which subject matter track?

**Comment by amwhitty** [comment]
@JustinAllisonUSDS Do you want me to map the new list of fields of expertise to subject matter tracks?

**Comment by LisaHwang** [comment]
Hi @amwhitty, the talent team leadership has asked to be apart of the discussion before we make any changes. @jvidaurri-usds @Nguhit @JustinAllisonUSDS

**Comment by 0kl-usds** [comment]
per some slack messages @LisaHwang and @jvidaurri-usds we should move this forward now

**Comment by ChristineWinchester-USDS** [comment]
@JustinAllisonUSDS @LisaHwang 
[Self-Selected Track to Subject Matter Track.xlsx](https://github.com/usds/website/files/12467826/Self-Selected.Track.to.Subject.Matter.Track.xlsx)

**Comment by LisaHwang** [comment]
9/8 This has now moved to production and is LIVE! You can check it out by going to usds.gov/apply
@amwhitty @0kl-usds @jvidaurri-usds
