### ISSUE TITLE
Configure large stat figures on impact report

### ISSUE THREAD

**Issue by amwhitty** [usds/website#963]
Is it possible to replicate the [big state/by the numbers style on project pages](https://www.usds.gov/projects/ssa) to be used on impact report pages?

The goal is to have these 4 impact report pages have large stat figures. I tried putting the stats in the SSA page like a project page, but that seems wrong.
https://usds.github.io/website-staging/impact-report/2024/ssa/
https://usds.github.io/website-staging/impact-report/2024/covid-reporting/
https://usds.github.io/website-staging/impact-report2024/medicaid-renewals/
https://usds.github.io/website-staging/impact-report/2024/medicaid-renewals/

Let me know if this is possible to potentially resolve by Wed 5/8. Thank you.

**Comment by TomNUSDS** [comment]
@amwhitty 
It has to do with the _template_ used for the various pages.

I can probably copy the "stats" template code over and get it working.

Let me look into it and I can let you know by tomorrow.

**Comment by TomNUSDS** [comment]
One issue is how the layout would look. The "right side" is taken up by the nav on the Reports to Congress:
<img width="706" alt="image" src="https://github.com/usds/website/assets/74203452/cc7a2358-d5d2-4d00-9a8b-6daeff51eb0c">


But so are the figures:
<img width="701" alt="image" src="https://github.com/usds/website/assets/74203452/6390a9ac-125c-47bc-bf73-f2b331fb8447">

"nesting" on inside the other might be odd looking?

**Comment by amwhitty** [comment]
@TomNUSDS Yes I agree have the left vertical stats and the left vertical nav won't work. Is it possible to take the text style but layout horizontal? Don't spend too long on this. Was mostly inquiring if it's a relatively simple enhancement.  I can just add a "by the numbers" header and use the stats in a bulleted list like the rest of the text.

**Comment by TomNUSDS** [comment]
Interesting. The mobile view of the "Figures" looks like this:


![Image](https://github.com/usds/website/assets/74203452/e7c67278-1617-40c5-a07b-3afd43242a96)


We could try to mix them. It might be a challenge css layout wise?

Would you want to appear at the top or bottom of the report?

**Comment by TomNUSDS** [comment]
https://www.usds.gov/report-to-congress/2017/fall/immigration-system/ has an impact section in it. But it's hacked as inline html in the markdown.

# Preview
![Image](https://github.com/usds/website/assets/74203452/2eb74e1b-8989-4e57-854a-8840400fb41c)


# Source
```html
### Impact

<div class="margin-bottom-3">
  <div>
    <span class="text-primary text-bold font-body-3xl">5</span>
    <span class="text-primary text-bold font-body-2xl">%</span> 
    <span class="text-primary text-bold font-body-3xl"> &rarr; 50</span>
    <span class="text-primary text-bold font-body-2xl">%</span>
  </div>
  <div>Increase in immigration workload completed digitally</div>
</div>

<div class="margin-bottom-3">
  <div>
    <span class="text-primary text-bold font-body-3xl">100</span>
    <span class="text-primary text-bold font-body-2xl">%</span>
  </div>
  <div>of new N-400 applications electronically processed since late Oct. 2017</div>
</div>
```

# My example
Here's what I've hacked together that uses Impact sections from the header:


![Image](https://github.com/usds/website/assets/74203452/5c73fc57-24b3-4d6b-8bd7-ae62cf812267)

**Comment by TomNUSDS** [comment]
Pull request here: https://github.com/usds/website/pull/964
