### ISSUE TITLE
footer grid breaking at an odd place for medium screen size

### ISSUE THREAD

**Issue by mollieru** [usds/website#97]
Looks like something in the grid is off in the footer as the 4th column drops down prematurely on slightly less than full desktop view. 

also could use a little more vertical spacing between top and bottom rows when the columns collapse
![screen shot 2016-05-19 at 6 02 25 pm](https://cloud.githubusercontent.com/assets/3680494/15411164/f00c4590-1deb-11e6-8265-7dfa1e7adb40.png)

**Comment by mollieru** [comment]
This is unresolved -- looks like the break is still occurring.

**Comment by davidrkaufman** [comment]
@cew821 - is this an easy fix?
